<? $rowNum = $this->element->rownumber->getValue(); ?>
<?php $view = $this->element->rownumber->getView(); ?>
<table class="formInput" style="width:625px;" cellpadding="0" cellspacing="0" id="other_services_<?= $rowNum; ?>">
    <tr>
		<td style="width:5px;">
		<?php echo $this->element->id_form_013_other_services; ?>
		<div>
			<?php echo $this->element->id_form_013_other_services; ?>
			<?= $rowNum; ?>.
		</div>
		</td>
		<td style="width:100px;">
		<strong><?php echo $this->element->other_service->getLabel(); ?></strong>
		<div id="other_services_<?= $rowNum; ?>-other_service-colorme" class="colorme">
			<?php echo $this->element->other_service; ?>
		</div>
		</td>
		<td style="width:100px;">
		<strong><?php echo $this->element->other_service_start->getLabel(); ?></strong> <br />
		<span  id="other_services_<?= $rowNum; ?>-other_service_start-colorme" class="colorme">
		<?php echo $this->element->other_service_start; ?>
		</span> / 
		<td style="width:100px;">
		<strong><?php echo $this->element->other_service_end->getLabel(); ?></strong>
		<div id="other_services_<?= $rowNum; ?>-other_service_end-colorme" class="colorme">
		<?php echo $this->element->other_service_end; ?>
		</div>
		</td>
		<td class="smallInput noprint" style="width:75px;">
		<div id="other_services_<?= $rowNum; ?>-remove_row-colorme" class="colorme">
        <?php echo $this->element->remove_row; ?>
        </div>
		</td>
    </tr>
    <tr>
        <td style="width:5px;">
            &nbsp;
        </td>
        <td colspan="1">
		<strong><?php echo $this->element->other_person_responsible->getLabel(); ?></strong>
		<div id="other_services_<?= $rowNum; ?>-other_person_responsible-colorme" class="colorme">
			<?php echo $this->element->other_person_responsible; ?>
		</div>
		</td>
		<td colspan="2">
		<strong><?php echo $this->element->other_funding_source->getLabel(); ?></strong>
		<div id="other_services_<?= $rowNum; ?>-other_funding_source-colorme" class="colorme">
			<?php echo $this->element->other_funding_source; ?>
		</div>
		</td>
    </tr>
</table>
<br />