<?php 
echo '<div class="page1Landscape"><div class="confidential">Confidential</div>';
    echo $this->header;
    echo $this->footer;
//    echo $this->student_header;
    echo $this->pages [1] . '</div>';

echo '<div class="page2Landscape">'.$this->pages[2].'</div>';
echo '<div class="page3Landscape"><div class="confidential">Confidential</div>'.$this->pages[3].'</div>';
echo '<div class="page4Landscape"><div class="confidential">Confidential</div>'.$this->pages[4].'</div>';
echo '<div class="page5Landscape">'.$this->pages[5].'</div>';
echo '<div class="page6Landscape">'.$this->pages[6].'</div>';
echo '<div class="page7Landscape" style="page-break-before:always;page-break-after:always;"><div class="confidential">Confidential</div>'.$this->pages[7].'</div>';
echo '<div class="page8Landscape"><div class="confidential">Confidential</div>'.$this->pages[8].'</div>';
echo '<div class="page9LandscapeIfsp">'.$this->pages[9].'</div>';
