<? $rowNum = $this->element->rownumber->getValue(); ?>
<?php $view = $this->element->rownumber->getView(); ?>
<table class="formInput printCellUnderlineThinPaddedTable" style="width:100%;" cellpadding="0" cellspacing="0" id="meeting_participation_<?= $rowNum; ?>" style="margin-top:1px;" width="60%">
	<tr>
		<td style="width:5px;">
		<?php echo $this->element->id_form_028_meeting_participation; ?>
		<div>
			<?php echo $this->element->id_form_028_meeting_participation; ?>
			<?= $rowNum; ?>.
		</div>
		</td>
		<td style="width:100px;">
		<?php echo $this->element->id_form_028_meeting_participation; ?>
		<div id="meeting_participation_<?= $rowNum; ?>-full_name-colorme" class="colorme
		    <? if('' == $this->element->full_name->getValue()): ?> printCellUnderlineThinPadded<? endif ;?>">
			<?php echo $this->element->full_name; ?>
		</div>
		</td>
		<td class="smallInput" style="width:100px;">
		<div id="meeting_participation_<?= $rowNum; ?>-role-colorme" class="colorme
		    <? if('' == $this->element->role->getValue()): ?> printCellUnderlineThinPadded<? endif ;?>">
		<?php echo $this->element->role; ?>
		</div>
		</td>
		<td class="smallInput" style="width:75px;">
		<div id="meeting_participation_<?= $rowNum; ?>-meeting_date-colorme" class="colorme
		    <? if('' == $this->element->meeting_date->getValue()): ?> printCellUnderlineThinPadded<? endif ;?>">
		<?php echo $this->element->meeting_date; ?>
		</div>
		</td>
		<td class="smallInput noprint" style="width:75px;">
		<div id="meeting_participation_<?= $rowNum; ?>-remove_row-colorme" class="colorme">
        <?php echo ($rowNum != 1 && $rowNum != 2) ? $this->element->remove_row : ''; ?>
        </div>
		</td>
    </tr>
</table>
