<? $rowNum = $this->element->rownumber->getValue(); ?>
<?php $view = $this->element->rownumber->getView(); ?>
<table class="formInput" style="width:100%;" cellpadding="0" cellspacing="0" id="parents_<?= $rowNum; ?>" style="margin-top:1px;" width="60%">
	<tr>
		<td style="width:125px;">
		<?php echo $this->element->id_form_028_parents; ?>
		<div id="parents_<?= $rowNum; ?>-parent_name-colorme" class="colorme">
			<?php echo $this->element->parent_name; ?>
		</div>
		</td>
		<td class="smallInput" style="width:125px;">
		<div id="parents_<?= $rowNum; ?>-home_phone-colorme" class="colorme">
		<?php echo $this->element->home_phone; ?>
		</div>
		</td>
		<td class="smallInput" style="width:125px;">
		<div id="parents_<?= $rowNum; ?>-work_phone-colorme" class="colorme">
		<?php echo $this->element->work_phone; ?>
		</div>
		</td>
		<td class="smallInput" style="width:125px;">
		<div id="parents_<?= $rowNum; ?>-email_address-colorme" class="colorme">
		<?php echo $this->element->email_address; ?>
		</div>
		</td>
		<!-- 
		<td class="smallInput" style="width:100px;">
		<div id="parents_<?= $rowNum; ?>-remove_row-colorme" class="colorme">
        <?= $this->element->remove_row; ?>
        </div>
		</td>
		-->
    </tr>
</table>