<?php 
	$view = $this->element->page->getView();
	echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
	echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_006; ?>
<?= $this->element->page; ?>
    
<table class="formTitleHead noprint" cellspacing="0" cellpadding="0">
   <tr>
        <td>Notice of School District's Decision Regarding Requested 
        Special Education Services</td>
    </tr>
</table>
<br>
<table class="formInput" style="margin-top:1px;">     
    <tr>
        <td>
        <strong><?php echo $this->element->date_notice; ?></strong><br>
	
	<?php // This is how you import parents.
	echo $view->db_form_data['student_data']['parents']; ?>
        </td>
    </tr>
    <tr>
     
        <?php 
		$urll=$_SERVER['REQUEST_URI'];
		$url_page = explode('/',$urll);
	
		 $displ= $url_page[2];
		//echo $displ;
		 $words =  "<b><i> (describe action proposed or refused)";
		 
		
        ?> 
        <td><b>
			You have requested that <?php echo $view->db_form_data['student_data']['name_district']; if ($displ=='edit') {
			    echo $words;
			}?>: </b><blockquote>
			<?php echo $this->element->describe_action; ?>
		</blockquote></td>
    </tr>
    
    
</table> 
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td>
		<div id="reason_wrapper-colorme" class="colorme">
		<b>The reason the school district
            <?php 
            if('print' == $view->mode) {
            	$option = $this->element->proposition_reason->getValue();
            	echo $this->element->proposition_reason->getMultiOption($option);
            } else {
                echo $this->element->proposition_reason; 
            } ?>
            to take this action is:</b>
        </div><blockquote>
	   <?php echo $this->element->describe_reason; ?></blockquote>
		</td>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td><b>
			The school district considered the following option(s):</b><blockquote>
			<?php echo $this->element->options_considered; ?>
		</blockquote></td></b>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td>
		<div id="proposition_wrapper-colorme" class="colorme">
			<b>The options were
            <?php 
            if('print' == $view->mode) {
                $option = $this->element->proposition_option_accept->getValue();
                echo $this->element->proposition_option_accept->getMultiOption($option);
            } else {
                echo $this->element->proposition_option_accept; 
            } ?>
            because:</b>
		</div><blockquote>
		<?php echo $this->element->options_rejected; ?>
	</blockquote>	</td>
    </tr>
</table>
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td><b>
			This decision is based on the evaluation procedures, tests, records, 
            or reports described below:</b><blockquote>
			<?php echo $this->element->decision_based; ?>
		</blockquote></td>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td>
		<b>	Any other factors relevant to the district's decision are:</b><blockquote>
			<?php echo $this->element->other_factors; ?>
	</blockquote>	</td>
    </tr>
</table> 

<table class="formInput" style="margin-top:1px;">     
    <tr>
        <td colspan="2"><b>
        Parents of children with disabilities have rights which are protected under the procedural safeguards of the Individual with Disabilities Education Act (IDEA). If you would like a copy of your procedural safeguards, or if you have any questions regarding this notice or your rights, you may contact:
       </b> </td>
    </tr><br>
    <tr><b>
		<td>
			<?php echo $this->element->contact_name; ?>
		</td>
		<td>
			<?php echo $this->element->contact_num; ?>
		</td></b>
    </tr>
</table> <br><br>

<b>
<?php echo $this->additionalResources(); ?>
