<?php /* 
<table class="formDesc sc_subSectionHead">
    <tr>
        <td>
            <span class="btsb">
                <?= $this->element->subformTitle->getValue(); ?>&nbsp;
                <?= $this->element->count;?>
            </span>
            <?= $this->element->addrow; ?>
            <?= $this->element->add_subform_row; ?>
        </td>
        <td class="p2424 noprint" align="right">
            <div id="accomodations_checklist_hide_label" style="display:inline-block;">Check to Show Accommodations Checklist</div>
            <span class="btsb" style="display:inline-block;">
                <?php echo $this->element->accomodations_checklist_hide; ?>
            </span>
        </td>
    </tr>
</table>
 */ ?>
