<? $rowNum = $this->element->rownumber->getValue(); ?>
<table class="formInput noBorder" id="assist_tech_<?= $rowNum; ?>">
    <tr class="bgLight2">
        <td>
            <?= $rowNum; ?>.
        </td>
        <td>
        	<div id="assist_tech_<?= $rowNum; ?>-ass_tech-colorme" class="colorme">
            <?= $this->element->ass_tech; ?>
            </div>
        </td>
        <td class="noprint" align="right" >
            <div id="assist_tech_<?= $rowNum; ?>-remove_row-colorme" class="colorme">
            <?= $this->element->remove_row; ?>
            </div>
        	<?= $this->element->id_form_004_assist_tech; ?>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="assist_tech_<?= $rowNum; ?>-dates_wrapper-colorme" class="colorme">
            <?php echo $this->translate('Duration Dates From/To'); ?>: 
            <?= $this->element->assist_tech_from_date; ?> <?php echo $this->translate('to'); ?> <?= $this->element->assist_tech_to_date; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="assist_tech_<?= $rowNum; ?>-assist_tech_location-colorme" class="colorme">
            <?php echo $this->translate('Location'); ?> <?= $this->element->assist_tech_location; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="assist_tech_<?= $rowNum; ?>-tpd_wrapper-colorme" class="colorme">
            <?= $this->element->assist_tech_tpd; ?>&nbsp;
            <?= $this->element->assist_tech_tpd_unit; ?>
            </div>
            <div id="assist_tech_<?= $rowNum; ?>-days_wrapper-colorme" class="colorme">
            <?= $this->element->assist_tech_days_value; ?>&nbsp;
            <?= $this->element->assist_tech_days_unit; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="assist_tech_<?= $rowNum; ?>-assist_tech_calendar-colorme" class="colorme">
            <?php echo $this->translate('Does Service Follow School Calendar'); ?>? <?= $this->element->assist_tech_calendar; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3"><hr /></td>
    </tr>
</table>