<tr>
    <td class="print_bgWhiteSmall" style="text-align:left;padding-left: 8px;"><? echo $this->element->ass_tech; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->assist_tech_from_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->assist_tech_to_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;"><? echo $this->element->assist_tech_location; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->assist_tech_tpd . " " . $this->element->assist_tech_tpd_unit; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->assist_tech_days_value . " " . $this->element->assist_tech_days_unit; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->assist_tech_mpy; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->assist_tech_calendar->getValue(); ?></td>
</tr>
