<p><strong>5</strong> records were found, records <strong>1</strong> thru <strong>15</strong> are displayed.<p>
<?php //echo $this->paginationControl($this->records, 'Sliding', 'partials/pagination-control.phtml'); ?>
<ul class="pseudoTable">
	<li class="head">
   		<ul>
   			<li>Transfer</li>
   			<li>Name</li>
   			<li>Case Manager</li>
   			<li>Address</li>
   			<li>Phone</li>
   			<li> &nbsp; </li>
   		</ul>
   	</li>
   	<li class="odd">
	</li>
</ul>
<?php //echo $this->paginationControl($this->records, 'Sliding', 'partials/pagination-control.phtml'); ?>