<p><strong>5</strong> records were found, records <strong>1</strong> thru <strong>15</strong> are displayed.<p>
<?php echo $this->paginationControl($this->records, 'Sliding', 'partials/pagination-control.phtml'); ?>
<ul class="pseudoTable">
	<li class="head">
   		<ul>
   			<li>Transfer</li>
   			<li>SRS Student ID</li>
   			<li>Name</li>
   			<li>County</li>
   			<li>District</li>
   			<li>School</li>
   			<li>User Role</li>
   		</ul>
   	</li>
   	<li class="odd">
	</li>
</ul>
<?php echo $this->paginationControl($this->records, 'Sliding', 'partials/pagination-control.phtml'); ?>