<?$auth = Zend_Auth::getInstance();?>
<table border="0">
    <!-- logo row -->
    <tr>
        <td>
                <?php if($auth->hasIdentity()) echo $this->navigationTopTabs('simple'); ?>
        </td>
    </tr>
    <tr>
        <td>
                <?php if($auth->hasIdentity()) echo $this->navigationSubmenu('student'); ?>
        </td>
    </tr>
</table>


<div style="position: relative; width: 100%; height: 300px; text-align: center; padding: 50px 0;"><?=$this->msg?></div>