


<script src="/js/validate/jquery.validate.min.js"></script>
<script>
  jQuery("#changePasswordForm").validate({
    errorClass: "change-password-error",
    rules: {
      password: {
         required: true,
         minlength: 6
      },
      password_confirm: {
        equalTo: "#password" 
      }
    },
    highlight: function (element) {
      $(element).css('border', '2px solid #FDADAF');
      $('#changePasswordButton').prop('disabled', 'disabled');
    },
    unhighlight: function (element) {
      $(element).css('border', '1px solid #CCC');
      $('#changePasswordButton').prop('disabled', false);
    }
  });

  $(document).on("click", "#changePasswordButton", function () {

    $(this).prop("disabled", true);
    if ($('#changePasswordForm').valid()) {

       $.ajax({
              type       : "POST",
              url        : "/passwordchange/changepassword",
              cache      : false,
              data       : { 
                             'id_personnel':encodeURIComponent($('#id_personnel').val()), 
                             'newPassword':encodeURIComponent($('#password').val()) 
                           },
              dataType   : "json",
              success    : function(response) {
                $("#successSave").html(response.message).addClass("blueAlert").show({ effect: "fade", duration: 500 });
                setTimeout(function(){$('#successSave').hide({ effect: "fade", duration: 500 }).html(); $('#dialog2').dialog('close');}, 3000);
              }
       });
    } else return false;


    return false;
  }); 
</script>
	  
<div id="successSave"></div>
<form id="changePasswordForm">
  <input type="hidden" id="id_personnel" value="<?php echo $this->id_personnel ?>">
  <h2><i> <?php echo $this->fullName.". "?></i></br>
  Passwords must match and be sixs or more characters.</h2>
  <table style="width: 100%; margin: 0 auto; margin-top: 30px;">
    <tr><th>Password</th><td style="padding-top:10px;"><input type="password" id="password" name="password"></td><td></td><tr>
    <tr><th>Confirm password</th><td style="padding-top:10px;"><input type="password" id="password_confirm" name="password_confirm"></td><td></td><tr>
    <tr><th></th><td style="padding-top:10px;" colspan="2"><input type="button" value="Change Password" name="changePasswordButton" id="changePasswordButton" class="ui-button ui-widget ui-corner-all" style="padding: 2px;"></td></tr>
  </table>
</form>
	 
<div id="successSave"></div>

<div>

</div>
<!-- JavaScript: placed at the end of the document so the pages load faster -->
		<!-- jQuery library -->
		