<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

  <head>
    <title>Videos</title>
    <meta charset="utf-8">
    <!-- Viewport Meta Tag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  
   <style>
.bs-example  div[class^="col-md"] {
	border: 1px solid green;
	background: orange;
	text-align: center;
	padding-top: 8px;
	padding-bottom: 8px;
	} 
    div[class^="col-md"]{
	border: 1px solid green;
	background: lightblue;
}	
</style>



<body>

    <!-- YOUR CONTENT GOES HERE -->
    
	
<br><br>
<div class=container>
<div class="row">
<!-- https://recalll.co/app/?q=zend%20framework%20-%20Zend_Http_Client%20load%20content%20to%20iframe -->

<div class="col-md-12">

<base target="myframe">

<iframe width="800" height="600" name="myframe" allowfullscreen autoplay ></iframe>
<html>

    <head>
        <base target="myframe">
    </head>

    <body>
        <!-- <a href="https://iepdev.nebraskacloud.org">Iep Site</a>-->
        <a href="https://www.youtube.com/embed/78ZoEt-TJQc?rel=0">Wades Voice</a>
        
    </body>

</html>

</div>

</div>

</div>

    <!-- JavaScript: placed at the end of the document so the pages load faster -->
		<!-- jQuery library -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

		<!-- Popper -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

		<!-- Latest compiled and minified Bootstrap JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
       
       
       
  
  </body>