<script src="/js/validate/jquery.validate.min.js"></script>
<script src="/js/validate/additional-methods.min.js"></script>

 <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
            <td>
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('district');
                } ?>
            </td> 
        </tr>
    </table>

<style>
#srs_mainPane {
    top: 115px;
    border: none;
    overflow: visible;
    margin-left: 10px;
}
#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}
#mainFooter{
	 height: 0px;
    padding-bottom: 0; 
	display: none;
}
#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}

#tooltip_container {
	color: black;
	position: absolute;
	display: none;
	padding: 20px;
	max-width: 400px; /* need i.e. rule */
	background-color:gainsboro;
	-webkit-border-radius: 12px;
	-moz-border-radius: 12px;
	border-radius: 12px;
}

.tooltip-source-html { display: none; }
</style>
<script>

<script type="text/javascript">
$("document").ready(function() {
	$("#password").css("width","80%");
	$("#password_confirm".css("width","80%"))
}
	 
</script>

<H2><Center>Change Password for <B><?php echo $this->fullName.". "?>
</B><p> Passwords must match and be six or more characters.</h2>
<br>
<br>


<?php echo $this->messages; ?>
<br><center>
 <?php  echo $this->form ?>
    
</center>

