<?php
$this->title = "Edit Districts";
$this->headTitle($this->title);
?>


<script type="text/javascript">
    $(document).ready(function() {
      $('#srs_mainPane').css('margin-left', "10px");
    });
</script>
<?php if ($this->message) { ?>
    <div class="message"><?= $this->message ?></div>
<?php } ?>

    <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('home');
                } ?>
            </td>
        </tr>
    </table>


    <table style=";" align="left" border="0">
        <tr>
            <td colspan="2" class="btsBig" align="center"><b>Welcome to the newer SRS home page.</b><br><br>
            </td>
        </tr>
        <tr>
            <td align="center" valign="top">
                <table border="0" style="width:450px;">
                    <?
                    echo "<tr><td colspan=\"2\" class=\"btbRed\" >";
                    // ADDED MESSAGE FOR NEW PRIVILAGE 030324-JL
                    // ===========================================
                    if(isset($option) && $option == 4) echo "To apply for a new privilege, select Edit Profile, then New Privilege.";
                    // ===========================================
                    echo "</tr></TD>";
                    ?>
                    <tr class="bgDark"><td align="center" nowrap="nowrap" style="height:19; width:10px;" colspan="2" class="menuTextBig"><B>Announcement Center</B></td><tr>
                    <tr class="bgLGrey">
                        <td align="center" nowrap="nowrap" style="height:19; width:1px;"><a href="/home/message-center" class="menuTextLinkBig" style="text-decoration:underline;"  >View Message Archive</a></td>
                        <td align="center" nowrap="nowrap" style="height:19; width:1px;"><a href="/home/message-center" class="menuTextLinkBig" style="text-decoration:underline;"  >Search Message Archive</a></td>
                    </tr>
                    <tr class="btGrey"><td colspan="2" class="bts">Messages below were created in the last week or are required to stay posted. Click 'View Message Archive' to see all messages. Click 'Search Message Archive' to search all messages. </td></tr>
                    <tr class="btGrey"><td colspan="2" class="bts"><img src='images/line_grey.gif' height=3 width='50%'></td></tr>
                    <tr>
                        <?
                        if (isset($numRows) && $numRows) {
                            for ($i = 0; $i < $numRows; $i++) {
                                $arrData = pg_fetch_array($result, $i);
                                if ($arrData['msg_type'] == "Warning") {
                                    $cssClass = "btsbRed";
                                } else {
                                    $cssClass = "bts";
                                }
                                if($arrData['msg_type'] == "Announcement") {
                                    $viewLink = " | <a href=\"srs.php?&area=home&sub=announcements&msgID=".$arrData['id_messages']."\"";
                                    $viewLink .= windowStatus('View this announcement');
                                    $viewLink .= ">View</a>";
                                } else {
                                    $viewLink = "&nbsp;";
                                }
                                echo "<tr><td class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j]>" . htmlEncode($arrData['msg_type']) . "</td><td class=\"$cssClass\" align=\"right\">".htmlEncode($arrData['create_date']).$viewLink."</tr>\n";
                                echo "<tr><td class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j] colspan=\"2\">\t" . htmlEncode($arrData['msg_title']) . "</td></tr>\n";
                                if($arrData['msg_type'] == "Warning") {
                                    echo "<TR><td colspan=\"3\" class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j] >" . htmlEncode($arrData['message_text']) . "</td></TR>\n";
                                }
                                echo "<tr>\n<td colspan=\"" . (count($arrFieldLabels) + 1) . "\"><img src='images/line_grey.gif' height=1 width='100%'></td>\n</tr>\n";
                            }
                        }
                        ?>
                </table>
            </td>
        </tr>
        <tr>
            <td align="center" colspan="2" class="btsBig"><BR><BR><i>This site is best viewed with a browser resolution of 1024x768 or greater.</i>
            </td>
        </tr>
    </table>

<style>
#DistrictDemographics  {
    width:400px;
    float:left;
    padding:10px;
	color:blue;
	font-weight:bold
	font-size:0.85em
}
#DistrictSettings {
    width:600px;
    float:left;
    padding:10px;
	color:green;
	font-size:0.85em
	font-weight:bold
}

#OptionalFeatures {
    width:500px;
    float:left;
    padding:10px;
	color:purple;
	font-size:0.85em
	font-weight:bold
}

#IepSummaryFormA {
    width:500px;
    float:left;
    padding:10px;
	color:red;
	font-size:0.85em
	font-weight:bold
}

</style>

<?php

//echo "<table>";
// for($x=1;$x< $this->staffCount;$x++) { 
//    echo "<tr><td>";
// echo $this->districtStaff[$x]['email_address']; echo "</td>";
  //  echo "</tr>";
//} 
//echo "</table>";

echo $this->current_date_and_time;
echo $this->noDecorators;
echo $this->form;
?>






