<?php
$view = $this->element->page->getView();

echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_026; ?>
<?=$this->element->page; ?>
<table class="formTitleHead" cellspacing="0" cellpadding="0">
	<tr class="noprint">
        <td>Prior Written Notice: Revocation of Consent for Special Education and Related Services</td>
	</tr>
</table>
<? if('print'!=$view->mode) { ?>
<table class="formInput" style="padding-bottom: 10px;text-align: left">
    <tr>
    	<td>Date of Notice/Discontinuation: <?php echo $this->element->date_of_notice_discontinuation; ?></td>
    </tr>
</table>
<?php } ?>
<table class="formInput" style="padding-bottom: 10px;text-align: left">
    <tr>
    	<td>Dear Parent/Guardian:</td>
    </tr>
    <tr> 
		<td>On <?php echo (''!=$view->db_form_data['parent_sig_on_file_date']) ? $view->db_form_data['parent_sig_on_file_date'] : '__/__/__'; ?>, you completed a Revocation of Consent for Special Education and Related Services document, advising the <?php echo $view->db_form_data['name_school']; ?> that it was your intent to revoke consent for the continued provision of special education and related services to your child. </td>
	</tr>
	<tr>
		<td>The District is required by federal law, Individuals with Disabilities Education Act (IDEA), and it's regulations to provide prior written notice before ceasing the provision of special education and related services.  The purpose of this Prior Written Notice is to provide you, the parent/guardian with information to make an informed decision when considering the written revocation of consent for special education and related services and provide information regarding the implications of this decision. </td>
 	</tr>
	<tr>
		<td>Based upon receipt of your revocation of consent, the district will discontinue all special education and related services for your child effective upon the issue date of this letter.  As this time, the services and education supports agreed to in your child's most current Individual Education Program (IEP) will no longer be available to your child.  
State and federal regulations provide protections and procedural safeguards for parents of students with disabilities; a statement of those protections and procedural safeguards (Parental Rights in Special Education) is enclosed with this Prior Written Notice.  By your revocation of consent, your child will no longer be entitled to the special education and related services and protections under the IDEA and relation provisions of the Nebraska Rule 51.  Your child will be treated as a general education student in all aspects, including in the event of any disciplinary action.  
Your revocation of consent releases the district from liability for providing your child with a free appropriate public education (FAPE).  If, at any time following the revocation, you wish to have your child considered for special education and related services, you may contact staff at your child's school with your request for evaluation.</td>    	
    </tr>
</table>
<table class="sc_formInputBlock">
	<tr class="bgLight3">
		<td class="btsb">A description of the action proposed by the district:</td>
	</tr>
	<tr class="sc_richTextBox">
		<td>
			<?php
			echo $this->element->description_of_the_action;
			?>
		</td>
	</tr>
</table>
<table class="sc_formInputBlock">
	<tr class="bgLight3">
		<td class="btsb">Explanation of why the action is proposed:</td>
	</tr>
	<tr class="sc_richTextBox">
		<td>
			<?php
			echo $this->element->explanation_of_why;
			?>
		</td>
	</tr>
</table>
<table class="sc_formInputBlock">
	<tr class="bgLight3">
		<td class="btsb">Options considered and why the options were rejected:</td>
	</tr>
	<tr class="sc_richTextBox">
		<td>
			<?php
			echo $this->element->options_considered;
			?>
		</td>
	</tr>
</table>
<table class="sc_formInputBlock">
	<tr class="bgLight3">
		<td class="btsb">Description of the evaluation procedure, assessment, record or report used as a basis for the proposed or refused action:</td>
	</tr>
	<tr class="sc_richTextBox">
		<td>
			<?php
			echo $this->element->description_of_evaluation;
			?>
		</td>
	</tr>
</table>
<table class="sc_formInputBlock">
	<tr class="bgLight3">
		<td class="btsb">Other factors relevant to the proposal:</td>
	</tr>
	<tr class="sc_richTextBox">
		<td>
			<?php
			echo $this->element->other_factors;
			?>
		</td>
	</tr>
</table>
<table class="formInput" style="padding-bottom: 10px;text-align: left">
	<tr>
		<td align="center">
		<strong>ADDITIONAL INFORMATION:</strong> You may contact any of the following resources to help you understand the federal and state laws for educating children with disabilities and parental rights (procedural safeguards) granted by those laws:  
		</td>
	</tr>
	<tr>
		<td align="center">
			<strong><?php echo $view->add_resource1; ?></strong><br />
			<strong><?php echo $view->add_resource2; ?></strong>
		</td>
	</tr>        
</table>                       