<script src="/js/validate/jquery.validate.min.js"></script>
<script src="/js/validate/additional-methods.min.js"></script>

<style>

th {
        font-weight:bold;
    }

#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}

#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}
.TableList tbody tr:hover td {
    background: 		#F4A460;
    }
	
</style>
<script type="text/javascript">
        $("document").ready(function() {
        	$(".paginationControl").css("width","80%");
        	 
            $(".paginationControl").css("font-size",'14px');
            $(".paginationControl").css("margin-bottom",'14px');
            $(".paginationControl").css("margin-top",'14px');
            $(".paginationControl").css("float",'left'); 

             $(".TableList").css("width","80%");
       	$(".TableList").css("border", "4px solid LightSkyblue");
       	$(".Tablelist th").css('width','50px');
       	$(".Tablelist td").css('width','50px');
      	$(".TableList").css("font-size","14px");
        $(".TableList a").css("color","MidnightBlue");
        $(".TableList  tr:even").css("background-color","LightSteelBlue");
        $(".TableList tr:odd").css("background-color","bisque");
        
        
        
        });
    </script>
    
    <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
            <td>
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('district');
                } ?>
            </td>
        </tr>
    </table>

<?php include("Writeit.php"); //writevar($this->person,'this is what is in the person array \n'); ?>

<?php if ($auth->hasIdentity()) { ?>


<?php  echo $this->current_date_and_time; ?><br>

<?  
   }    
?> 


<table class="TableList">
<tr >
    <th >
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfireport','fieldname'=>'name_district', "sort" => $this->sort ));?>>District's Name</a>
    </th>
     <th>
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfireport','fieldname'=>'id_county', "sort" => $this->sort));?>>County ID</a> 
    </th>
    <th>
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfireport','fieldname'=>'id_district', "sort" => $this->sort));?>>District ID</a> 
    </th>
    <th>
        Success
    </th>
    <th>
        Errors
    </th>
    <th>
        Waiting
    </th>
     <th>
        Hold
    </th>
    <th>
        No State ID
    </th>
</tr>
<tbody>
<style>

</style>
<?php 
   foreach($this->districtModel as $district) {?>
<tr>
 <td>
     <a  href="<?php echo $this->url(array('controller'=>'district','action'=>'edfidetail',
                    'id_district'=>$district['id_district'],
                    'id_county'=>$district['id_county']
                     ), null, true); ?>">
           <?php echo $this->escape($district['name_district']);?>
    </a>
 </td>
 <td style='text-align:center;'>
    <?php echo $this->escape($district['id_county']);?>
    </td>
    <td style='text-align:center;'>
    <?php echo $this->escape($district['id_district']);?>
    </td>
 <td style='text-align:center;'>
    <?php echo $this->escape($district['cok']);?>
</td>
<td style='text-align:center;'>
    <?php echo $this->escape($district['cerr']);?>
</td>
<td style='text-align:center;'>
    <?php echo $this->escape($district['cpen']);?>
</td>
<td style='text-align:center;'>
    <?php echo $this->escape($district['chold']);?>
</td>
<td style='text-align:center;'>
    <?php echo $this->escape($district['cnostate']);?>
</td>

</tr> 
<?}?>
</tbody>
</table>

<center><?php echo $this->paginationControl($this->districtModel,'sliding','sqlpaginator.phtml', array('route'=> 'district')); ?> </center>