<script src="/js/validate/jquery.validate.min.js"></script>
<script src="/js/validate/additional-methods.min.js"></script>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" >
</script>

<style>

#ResultsTable {
    font-size:0.7em;
}

.ui-accordion-header .ui-icon {
    display: block;
    position: relative;
}

.ui-accordion-header .ui-header {
    display: block;
    position: relative;
    margin-left: 25px;
    font-size: 14px;
    font-weight: 700;
}

#searchAlphabetArea {
    position: relative;
    font-weight: 700;
}

#searchArea {
    position: relative;
    width: 300px;
}

#searchAlphabet {
    position: absolute;
    top: 0px;
    left: 0px;
    width: 300px;
}


#cancelSearch {
    position: absolute;
    top: 0px;
    right: 0px;
    color: #a0a0a0;
    cursor: pointer;
}

#ResultsTable th {
        font-weight:bold;
        padding:2px;
    }

#ResultsTable td {
        padding:2px;
    }

.CellTable {
    border: width 0px;
    border-style: none;
    padding:0px;
    background-color: red;
}

.CellTable td th {
    padding:0px;
    background-color: red;
}


#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0;
}

#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px;
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}
.TableList tbody tr:hover td {
    background: 		#F4A460;
    }

</style>
<?php
function writevar1($var1,$var2) {

    ob_start();
    var_dump($var1);
    $data = ob_get_clean();
    $data2 = "-------------------------------------------------------\n".$var2."\n". $data . "\n";
    $fp = fopen("/tmp/textfile.txt", "a");
    fwrite($fp, $data2);
    fclose($fp);
}


$studentsJq = substr($this->studentsJqueryArray, 2);
?>


<script type="text/javascript">




            $("document").ready(function() {
        	$(".paginationControl").css("width","80%");

            $(".paginationControl").css("font-size",'14px');
            $(".paginationControl").css("margin-bottom",'14px');
            $(".paginationControl").css("margin-top",'14px');
            $(".paginationControl").css("float",'left');


        $(".TableList").css("width","80%");
       	$(".TableList").css("border", "4px solid LightSkyblue");
       	$(".Tablelist th").css('width','50px');
       	$(".Tablelist td").css('width','50px');
      	$(".TableList").css("font-size","14px");
        $(".TableList a").css("color","MidnightBlue");
        $(".TableList  tr:even").css("background-color","LightSteelBlue");
        $(".TableList tr:odd").css("background-color","bisque");


        $(".tableCell").css("width","100%");
        $(".TableList").css("font-size","0.9em");
        $(".tableCell  tr:even").css("background-color","transparent");
        $(".tableCell tr:odd").css("background-color","transparent");
        $(".tableCell td").css("border-bottom", "1px solid silver");


    	// Mike added 3-16-2018 so that we can search for students
        $(document).on( "click", "#cancelSearch", function() {
            $("#searchAlphabet").val("");

            $("#searchTable").html("");
            $("#searchTable").hide();
           $("#originalTable").show();
    	    return false;
        });



        $(document).on( "keyup", "#searchAlphabet", function() {
            var searchAlphabet = $.trim($("#searchAlphabet").val());
            var searchAlphabetLength = searchAlphabet.length;
            console.log(searchAlphabetLength);
            var studentsArrayList = [ <?= $studentsJq ?> ];


            if (searchAlphabet == "") {
    	    $("#searchAlphabet").val("");
    	    $("#searchTable").html("");
    	    $("#searchTable").hide();
    	    $("#originalTable").show();
             } else if ( searchAlphabetLength > 0 && searchAlphabet != "" ) {
    	    $("#searchTable").html("");
    	    $("#originalTable").hide();
    	    $("#searchTable").show();

    	    var i = 0;
    	    var color = "#B0C4DE";
    	    var finded = 0;
    	    var searchRes = "";
            console.log(studentsArrayList[0]);
        	$.each(studentsArrayList, function(key, val) {

    	        color = (finded % 2) ? "#B0C4DE" : "#FFE4C4";
    		if (i == 0){

            	    searchRes += '<table class="TableList" border="4px solid LightSkyblue">';
            	    searchRes += '<tr style="background-color: lightsteelblue"><b><th width="20%">Student and Ids</th><th width="10%">Org ID </th><th style="text-align:center;">Result</th><th>Error</th><th width="20%">School and Publish time</th><th width="20%">Dates/Reason exited </th><th width="20%">Details</th><br><br></b></tr>'





            	//	searchRes +='<tr bgcolor="red"><td>heading one<</td></tr>';
          		    searchRes += '<tbody>';
    		   }

    	        if ((val[1].substr(0, searchAlphabetLength)).toLowerCase() == searchAlphabet.toLowerCase()) {
    		    finded++;
    	       //     searchRes += '<tr bgcolor="' + color + '" class="TableRow"><td><b><a href="/district/view/name_district/' + encodeURIComponent(val[0]) + '/id_district/' + val[4] + '/id_county/' + val[3] + '">' + val[0] + '</a></b></td><td>' + val[1] + '</td><td>' + val[3] + '</td><td>' + val[3] + '</td><td>' + val[4] + '</td><td>' + val[5] + '</td><td>' + val[6] + '</td><td>' + val[7] + '</td><td style="width: 70px; padding: 2px;"><select class="options" title="' + val[0] + '"><option value="" selected>Choose...</option><option value="/district/viewdistrict/id_county/' + val[3] + '/id_district/' + val[4] + '/">View District</option></select></td></tr>';

                searchRes += '<tr bgcolor="' + color + '"><td><b>' + val[0] + ' ' + val[1] + '</b><br>Id Student:<b> '+ val[2]+ '</b><br>Unique Id State: '+ val[3] +'</td>';
                searchRes += '<td>' +val[4] + '</td>';
                if(val[5]=='E') clr='#FF0000';
                if(val[5]=='S') clr='#009933';
                if(val[5]=='X') clr='#CA9A52'
                if(val[5]=='W') clr='#800080';
                searchRes += '<td><span style="color:'+ clr +'"><center><b>' +val[5] + '</b></center></span></td>'; // Error code

                searchRes += '<td>' + val[6] +'</td>' // Error Message
                searchRes += '<td> School Name:<b>' + val[7] + '</b></br>';
                searchRes += val[8] + '</td>';
                searchRes += '<td> Begin Date: ' +val[9] +'<br>';
                searchRes += 'End Date: '+ val[10] + '<br>';
                searchRes += 'Reason Exited Desciptor: ' +val[11] + '<br>';
                searchRes +='<a href="/student/edit/id_student/'+ val[2] + '">Edit Student Link</a><br>';

                if(val[12]=='form004'){
                searchRes +='<a href=/form004/view/document/'+ val[13]+'/page/6">View Latest IEP</a><br>';
                }

                if(val[12]=='form023'){
                    searchRes +='<a href=/form023/view/document/'+ val[13]+'/page/1">View Latest IEP Card</a><br>';
                    }

                if(val[14]=='form002'){
                    searchRes +='<a href=/form002/view/document/'+ val[15]+'/page/3">View Latest MDT</a><br>';
                    }

                if(val[14]=='form022'){
                    searchRes +='<a href=/form022/view/document/'+ val[15]+'/page/1">View Latest MDT Card</a><br>';
                    }

                searchRes +='<a href="/student/search-forms/id_student/'+ val[2] +'">Search Student Forms</a><br><br></td>'


                // Do the Details column

                 searchRes +='<td>Special Ed Setting:<b> '+ val[16]+ '</b><br>';
                searchRes +='Level of Program Participation:<b> '+ val[17] + '</b><br>';
                searchRes +='Placement Type: <b>'+ val[18]+ '</b><br>';
                searchRes +='SPED Percent Time %: <b>'+val[19]+ '</b><br>';
                if(val[20]==0) altassment='No';
                if(val[20]==1) altassment='Yes';
                searchRes +='To Take Alt Assessment: <b>' + altassment +'</b><br>';
      // Mike changed this val[20] 4-3-2018 so that it would say yes or no.

                  //    searchRes +='To Take Alt Assessment: <b>'+ val[20]+ '</b><br>';
                searchRes +='Disabilities: <b>'+ val[21]+ '</b><br>';
                searchRes +='Speech Language: <b>'+ val[22]+ '</b><br>';
                searchRes +='Occupational Therapy: <b>'+ val[23]+  '</b><br>';
                searchRes +='Physical Therapy: <b>'+ val[24]+  '</b><br><br>';



                searchRes +'</td><tr>';



   	        }

    		if (i == studentsArrayList.length - 1) {
    		    searchRes += '</tbody>';
    		    searchRes += '</table><br><br>';
    		}

    	        i++;

    	    });
    	    $("#searchTable").html(searchRes)

        	    if (finded == 0) $("#findres").append('<center><br><br>No matches<br><br></center>');

             }

    	    return false;
        });
    //End of Mike add for search.






        });










    </script>

    <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
            <td>
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('district');
                } ?>
            </td>
        </tr>
    </table>

<?php //include("Writeit.php"); //writevar($this->person,'this is what is in the person array \n'); ?>

<?php if ($auth->hasIdentity()) { ?>


<?php  echo $this->current_date_and_time; ?><br>

<?
   }
?>
<script type="text/javascript">
$("document").ready(function() {

	document.getElementById("change").addEventListener("click", function (evt) {
        changeContent();
    });




});

function changeContent() {
    // use the html() function to change the content of the div
    var Message= $("<p><font size=\"+1\">Warning: Please wait until this message disappears before leaving this page. </p><p><font size=\"+1\">SRS is updating the State ODS with your Districts Data! </p>")
    $(".new").html(Message);

    $(".new").css("color","red");
}



</script>





<h2 id="change" class="new" ><a href="/ods/advisorset/id_county/<?php echo $this->countyId?>/id_district/<?php echo $this->districtId?>"> <b> Update ODS with Student's Data </b></a></h2>


<div id="searchAlphabetArea">
    Search by Last Name<br>
    <div id="searchArea">
        <input type="text" value="" id="searchAlphabet">
        <div id="cancelSearch"><i class="fa fa-times fa-lg"></i></div>
    </div>
</div>
<br>
<br>


<div id="searchTable"></div>

<div id="originalTable">
<center><?php echo $this->paginationControl($this->districtModel,'sliding','sqlpaginator.phtml', array('route'=> 'district')); ?> </center>

<table class="TableList" id="ResultsTable" width="100%">
<tr >
    <th width="20%">
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfidetail2','fieldname'=>'edfipublishtime', "sort" => $this->sort ));?>>Student and Ids</a>

    </th>
    <th width="10%">
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfidetail2','fieldname'=>'educationorganzationid', "sort" => $this->sort ));?>>Org ID</a>
    </th>
    <th style="text-align:center;">
        <a href =<?php echo $this->url(array('controller'=>'district','action'=>'edfidetail2','fieldname'=>'edfipublishstatus', "sort" => $this->sort ));?>>Result</a>
    </th>
    <th>
        Error
    </th>
    <th width="20%">
        School and Publish time
    </th>
    <th width="20%">
        Dates/Reason exited
    </th>
    <th width="20%">
        Details
    </th>
</tr>
<tbody>
<style>

</style>

<div id="searchTable"></div>

<div id="originalTable">
<?php
    foreach($this->districtModel as $district) {

        ?>
<tr >
    <td>
        <b><?php echo $this->escape($district['name_first'])." ".$this->escape($district['name_last'])?></b>
        <br>
        Id: <?php echo $this->escape($district['id_student']);?>
        <br/>
        Unique: <?php echo $this->escape($district['studentuniqueid']);?>
    </td>








    <td>
        <?php echo $this->escape($district['educationorganzationid']);?>
    </td>
    <td style="text-align:center;">
<b>
        <?php
         $color="";
         switch($district['edfipublishstatus']){
             case "X":
                 $color="#CA9A52";
                 break;

             case "S":
                $color="#009933";
                break;

            case "E":
                $color="#FF0000";
                break;

        };
        ?>

        <span style='color:<?php echo($color) ?>'><?php echo ($this->escape($district['edfipublishstatus'])) ?>  <span>

   </b>

    </td>
    <td>
        <?php
        $error_msg1="Authorization denied. The claim does not have any established relationships with the requested resource.";
        $replacement_msg1='The student does not seem to have an entry from your SIS.  Please check your SIS and make sure the student is being exported to the State ODS.';



        echo $this->escape($district['edfierrormessage']);?>
    </td>

   <td >
        School Name:<b><?php echo $this->escape($district['name_school']);?> </b><br>
        <?php echo $this->escape($district['edfipublishtime']);?>

    <td>
        Begin: <?php echo $this->escape($district['begindate']);?>
        <br>
        End: <?php
            echo $this->escape(  (($district['enddate']=="") ? "-" : $district['enddate']) );?>
        <br>
        Reason Exited Descriptor: <?php echo $this->escape($district['reasonexiteddescriptor']);?>
        <br>
        <a href="/student/edit/id_student/<?php echo $district['id_student']?>">Edit Student Link</a>
        <br>
        <?php if($district['iep_ifsp_code']=='form004'){
                   $iepFormName='Latest IEP';
                   $pageIep='6';
        }
              if($district['iep_ifsp_code']=='form023'){
                  $iepFormName='Latest IEP Data Card';
                  $pageIep='1';
              }
              if($district['mdt_code']=='form002'){
                  $mdtFormName='Latest MDT';
                  $pageMdt='3';
              }
              if($district['mdt_code']=='form022') {
                  $mdtFormName='Latest MDT Card';
                  $pageMdt='1';
              }

         //     echo $district['iep_ifsp_code'];
            ?>
        <a href="/<?php echo $district['iep_ifsp_code']?>/view/document/<?php echo $district['iep_ifsp_id']?>/page/<?php echo $pageIep?>">View <?php echo $iepFormName?></a>
        <br>
        <a href="/<?php echo $district['mdt_code']?>/view/document/<?php echo $district['mdt_id']?>/page/<?php echo $pageMdt?>">View <?php echo $mdtFormName?></a>
        <br>
        <a href="/student/search-forms/id_student/<?php echo $district['id_student']?>">Search Student Forms</a>
    </td>
    <td>
        <table class="tableCell">
            <tr>
                <td>
                    Special Ed Setting:
                </td>
                <td>
                    <?php echo $this->escape($district['specialeducationsettingdescriptor']);?>
                </td>
            </tr>
            <tr>
                <td>
                    Level Program Participation:
                </td>
                <td>
                    <?php echo $this->escape($district['levelofprogramparticipationdescriptor']);?>
                </td>
            </tr>
            <tr>
                <td>
                    Placement Type:
                </td>
                <td>
                    <?php echo $this->escape($district['placementtypedescriptor']);?>
                </td>
            </tr>
            <tr>
                <td>
                    SPED Percent Time  %:
                </td>
                <td>
                     <?php echo $this->escape($district['specialeducationpercentage']);?>
                </td>
            </tr>
            <tr>
                <td>
                    To Take Alt Assessment:
                </td>
                <td>
                <?php
                if($this->escape($district['totakealternateassessment'])=='1') $answer='Yes';
                if($this->escape($district['totakealternateassessment'])=='0') $answer='No';
                echo $answer;

               // echo $this->escape($district['totakealternateassessment']);?>

                </td>
            </tr>
            <tr>
                <td>
                    Disabilities:
                </td>
                <td>
                    <?php echo $this->escape($district['disabilities']);?>
                </td>

            </tr>
            <tr>
                <td>
                    Speach Language:
                </td>
                <td>
                    <?php echo $this->escape($district['servicedescriptor_slt']);?>
                </td>

            </tr>
            <tr>
                <td>
                    Occupational Therapy:
                </td>
                <td>
                    <?php echo $this->escape($district['servicedescriptor_ot']);?>
                </td>

            </tr>

            <tr>
                <td>
                    Physical Therapy:
                </td>
                <td>
                    <?php echo $this->escape($district['servicedescriptor_pt']);?>
                </td>

            </tr>


        </table><br>

    </td>
</td>

</tr>
<? } ?>
</tbody>
</table>

<center><?php echo $this->paginationControl($this->districtModel,'sliding','sqlpaginator.phtml', array('route'=> 'district')); ?> </center>

</div>