<script type="text/javascript">
        $("document").ready(function() {
       	$(".TableList").css("border", "4px solid LightSkyblue");
       	$(".TableList").css("font-size","80%");
           // $("#example p:first").css("border", "3px solid red");
          //  $("#example p:last").css("border", "3px solid red");
            $(".TableList a").css("color","MidnightBlue");
            $(".TableList  tr:even").css("background-color","LightSteelBlue");
            $(".TableList tr:odd").css("background-color","bisque");
          // $(".Tablelist > tr").css("font-size:10px");
            //$("#example p:odd").css("border", "3px solid red");
            //$("#example .a:first").css("border", "3px solid red");
            //$("#example .b:even").css("border", "3px solid red");
        //    $("#example p:gt(2)").css("border","3px solid red");
         //   $("#example p:lt(3)").css("border","3px solid clear");
         //  $("#example p:not(p:eq(2))").css("border", "3px solid red");
        });
    </script>
    
  <style>  
    .TableList {
        width: 80%;
    margin: 5px;
    }

    .TableList td {
    padding: 16px;
        border-bottom: 1px solid #f0f0f0;
    	font-size: 14px;
    }
    .TableList th {
        padding: 18px
    	font-size:14px;
        border-bottom: 1px solid #e0e0e0;
        font-weight: bold;
    }
    .TableList tbody tr:hover td {
    background: #FFF999;
    }
    
#srs_mainPane {
    top: 115px;
    border: none;
    overflow: visible;
    margin-left: 110px;
}
#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}

#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}

 .TableList tbody tr:hover td {
    background: #FFF999;
    }
</style>