<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
<html>
<head>
 <title><?=$this->result["name_first"]?> <?=$this->result["name_last"]?> (<?=$this->result["id_guardian"]?>)</title> 
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />  
 <link href="/css/srs_style_additions.css?refreshCode=20150826" media="screen" rel="stylesheet" type="text/css" />
 <link href="/css/srs_style_forms.css?refreshCode=20150826" media="screen" rel="stylesheet" type="text/css" />
 <!--[if IE 9]><link href="/css/srs_style_IE9.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
 <!--[if IE 8]><link href="/css/srs_style_IE8.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
 <!--[if IE 7]><link href="/css/srs_style_IE7.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
 <!--[if IE 6]><link href="/css/srs_style_IE6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
 <!--[if IE]><link href="/css/srs_style_IE.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
 <link href="/css/srs_style_forms.css?refreshCode=20150826" media="screen" rel="stylesheet" type="text/css" />
 <script type="text/javascript" src="/js/jquery/jquery-1.8.2.js"></script>

<head>
<body>

<script type="text/javascript">
  $(document).ready(function () {
    window.print();
  });
</script>