<?php 
    $view = $this->element->page->getView();
	echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
	echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_005; ?>
<?= $this->element->page; ?>

<table class="formTitleHead noprint" cellspacing="0" cellpadding="0">
   <tr>
        <td><b>Notice and Consent For Initial Placement in Special Education Services</b></td>
    </tr>
</table>
<table class="formInput">     
    <tr>
        <td>
        <?php echo $this->element->date_notice; ?>
        </td>
    </tr>
</table>
<table class="formInput"> 
    <tr>
		<td>
		<div id="dates_wrapper-colorme" class="colorme">
	<b>1: 	On <?php echo $this->element->date_met; ?>
		the Individual Education Program (IEP) Team met to develop an appropriate 
		educational program for your child.<br> To the maximum extent appropriate, your 
		child will be educated with other children in the general education 
		environment. <br>Your child will be moved from the general education environment 
		only when the nature or severity of needs are such that<br> the education in 
		general education classes with supplementary services cannot be achieved 
		satisfactorily. <br>Based on the IEP which has been developed for your child, 
        the Adama proposes to serve your child within the following 
        program<span class="noprint"> <br>(describe the proposed program)</b></span>:
        
		</div><blockquote>
		<?php echo $this->element->describe_program; ?></blockquote>
		</td>
	</tr>
</table>
<table class="formInput"> 
	<tr>
		<td>
	<b>2: The suggested special education program is based on<span class="noprint"> (describe the reasons 
        why the district proposes to place)</b></span>:
	<blockquote><?php echo $this->element->describe_reason; ?></blockquote>
		</td>
    </tr>
</table> 
<table class="formInput"> 
	<tr>
		<td><b>
		3: To determine the appropriate placement for your child, the school distric
        considered the following option(s) prior to reaching the placement decision,<br>
        and rejected those option(s) because<span class="noprint"> (provide a description of any options 
        the district considered and the reasons why those options were rejected)</b></span>:
	<blockquote>	<?php echo $this->element->provide_description; ?></blockquote>
		</td>
    </tr>
</table> 
<table class="formInput"> 
	<tr>
		<td>
		<b>4: The proposed placement is based upon the following evaluation procedures, tests, 
		
        records or reports:</b>
	<blockquote><?php echo $this->element->proposed_placement; ?></blockquote>
		</td>
    </tr>
</table> 
<table class="formInput"> 
	<tr>
		<td>
		<b>5: Other factors which are relevant to the school district's proposal, if any, are:</b>
	<blockquote>	<?php echo $this->element->other_factors; ?></blockquote>
		</td>
    </tr>
</table> 

<table class="formInput">
	<tr>
		<td colspan="2">
		<p><b>6: Parents of children with disabilities have rights which are protected under the procedural safeguards of the Individual with Disabilities Education Act (IDEA).
		 <br>If you would like a copy of your procedural safeguards, or if you have any questions regarding this notice or your rights, you may contact:</b>
		</td>
	</tr> 
	<tr>
		<td>
		<?php echo $this->element->contact_name; ?>
		</td>
		<td>
		<?php echo $this->element->contact_num; ?>
		</td>
    </tr>
</table> 
