<input type="hidden" name="returnResult" id="returnResult" value="" />
<input type="hidden" name="changePageAction" id="changePageAction" value="" />
<?= $this->element->id_form_033; ?>
<?= $this->element->page; ?>
<table class="formTitleHead" cellpadding="0" cellspacing="0" style="margin-bottom:1px;">
    <tr>
        <td>Annual Transition Notice</td>
    </tr>
</table>
<table class="formInput" class="formInput">
    <tr>
        <td colspan="2">
            <?php echo $this->element->date_notice; ?>
        </td>
    </tr>
</table>
<?
$view = $this->element->page->getView();
echo $this->partial('form033/staticInfo.phtml', array(
    'action' => $view->action,
    'mode' => $view->mode,
    'form' => $view->form
));

