<?php
$tableAtn = "border: 1px solid black;	border-collapse: collapse;";
$atn = "border: 1px solid black;padding: 3px;cell-spacing:0px;";
$atnb = "border: 1px solid black;padding: 3px;cell-spacing:0px;font-weight: bold;";
?><style>
    table.atn, div.atn {
        border: 1px solid black;
    }
    td.atnb, div.atnb {
        font-weight: bold;
    }
    td.atn, div.atn, td.atnb, div.atnb {
        border: 1px solid black;
        padding: 3px;
    }
</style>
    <div>
        Purpose: Transitions occur for children and families across their lifespan. One major transition required within
        IDEA is when children transition out of Part C Early Intervention Services. Families must be fully informed about
        the process and afforded their rights, responsibilities, and options surrounding transition. This notice is given to
        all families at their child’s first transition conference which must take place no less than 90 days prior to their
        third birthday, and, at the discretion of all parties, not more than 9 months before the child will no longer be
        eligible to receive, or no longer receives early intervention services. The information on this form is intended to
        help parents understand their rights and the procedural safeguards regarding their child’s services. The early
        intervention program shall continue to provide all early intervention services identified in the child’s IFSP under
        92 NAC 52-007 beyond age 3 until that child begins receiving preschool services under 92 NAC 51 (Part B services).
        Parents of children with disabilities also have the right to continue to receive early intervention services per 92
        NAC 52 through August 31st of their third birthday or preschool services pursuant to 92 NAC 51. The differences
        between Early Intervention Services/IFSP and Part B Services/IEP are as follows:
    </div>
    <table style="<?= $tableAtn ?>">
        <TR>
            <TD style="<?= $tableAtn ?>width:25%;"></TD>
            <TD style="<?= $atnb ?>width:38%;">Early Development Network - NDE 92 NAC 52/DHHS 480 NAC 3</TD>
            <TD style="<?= $atnb ?>">Preschool Special Education Program NDE 92 NAC 51</TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Ages of Children Served</TD>
            <TD style="<?= $atn ?>">Children, ages birth to August 31st of 3rd birthday</TD>
            <TD style="<?= $atn ?>">Children, ages three through twenty-one years</TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Individualized Plans</TD>
            <TD style="<?= $atn ?>">Individualized family service plan (IFSP)</TD>
            <TD style="<?= $atn ?>">Individualized education program (IEP)</TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Child’s Levels of Development</TD>
            <TD style="<?= $atn ?>">A statement of the child’s levels of development across all developmental domains, including
                vision, hearing, and health.
            </TD>
            <TD style="<?= $atn ?>">A statement of child’s present levels of academic achievement and functional performance.</TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Goals/Outcomes</TD>
            <TD style="<?= $atn ?>">Goals/Outcomes are: 1) based on the family’s concerns and desired priorities; 2) family centered
                and written in family friendly language with the criteria, process, and timeline for determining progress;
                and 3) may be related to the child, family, and community.
            </TD>
            <TD style="<?= $atn ?>">Goals are: 1) based on child’s needs as determined by the MDT and the observations of parents
                and school personnel; 2) academically and functionally centered;
                3) include objectives and benchmarks; and 4) include academic and functional goals related to meeting the
                child’s needs in the general curriculum and other educational needs related to the child’s disability.
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Educational Component</TD>
            <TD style="<?= $atn ?>">IFSP’s for children who are three years old must include an educational component that promotes
                school readiness and incorporates pre-literacy, language, and numeracy skills. Your services coordinator
                along with the rest of the IFSP team will help to determine how these components are already being addressed
                or what may need to be added to your plan to meet this requirement.
            </TD>
            <TD style="<?= $atn ?>">If a child continues to verify for services under Part B, the family along with the team will
                develop an Individualized Education Plan.
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Available Services</TD>
            <TD style="<?= $atn ?>">Early intervention services for child and family to meet the developmental needs of the child
                and increase the family’s ability to meet the needs of their child (examples listed in regulations).
            </TD>
            <TD style="<?= $atn ?>">Special education and related services determined appropriate to meet the educational needs of
                the child (examples of services listed in statute) and that enable the child—to the maximum extent
                possible—to participate in the general education curriculum.
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Family Involvement</TD>
            <TD style="<?= $atn ?>">Participation on all teams making decisions about the child’s individualized plan for
                services<BR/><BR/>
                Receive services to improve the family’s ability to meet the needs of their child with a disability
            </TD>
            <TD style="<?= $atn ?>">Participation on all teams making decisions about the child’s individualized plan for services
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Location for Services</TD>
            <TD style="<?= $atn ?>">Natural environment—to the maximum extent appropriate, the child is served in environments that
                are normal or natural for a child of that age (including the home and integrated child care settings)
            </TD>
            <TD style="<?= $atn ?>">Least restrictive environment—to the maximum extent appropriate, the child receives services and
                participates in the general curriculum, non-academic, and extra-curricular activities alongside peers
                without disabilities.
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Services Provided During Summer Months</TD>
            <TD style="<?= $atn ?>">Services determined on the IFSP are continuously provided throughout the year including the
                summer months.
            </TD>
            <TD style="<?= $atn ?>">For students with a disability, the IEP team must consider each individual student’s need for
                extended school year (ESY) services during time periods when other students, both with disabilities and
                without disabilities, normally would not be served. If ESY is determined to be necessary to enable the
                student to benefit from his or her education, the type and amount of special education services to be
                provided, including frequency, location, and duration are documented in the IEP. Schools must not limit the
                availability of ESY service to students in particular categories of disabilities or limit the type, amount,
                or duration of these necessary services (92 NAC 51 007.07C5).
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Services Coordinator</TD>
            <TD style="<?= $atn ?>">Each infant or toddler with a disability and the child’s family must be provided with one
                service coordinator who is responsible for coordinating all services required under IDEA Part C across
                agency lines; and serving as the single point of contact for carrying out the activities described in
                303.34(a)(3) and 303.34(b).
            </TD>
            <TD style="<?= $atn ?>">Services Coordinators are not provided in Part B services.</TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Transition</TD>
            <TD style="<?= $atn ?>">Transition is outlined in the steps to be taken to prepare for the successful change to new
                anticipated agencies, locations for services, providers, funding sources or models, etc.
            </TD>
            <TD style="<?= $atn ?>">Transition Services (school to adult life) or the transition plan must be written into the IEP
                no later than age 16 and continues through the year in which the student turns 21 or at termination of
                special education, whichever comes first.
            </TD>
        </TR>
        <TR>
            <TD style="<?= $atnb ?>">Procedural Safeguards</TD>
            <TD colspan="2" style="<?= $atn ?>">As outlined in the “rule 51, 52, 55”, as well as the Part C Procedural Safeguards
                and the Parental Rights in Special Education, which you have received a copy of and can request additional
                copies of at any time, parents have access to educational records (92 NAC 52 009.02C); rights to complaints
                (92 NAC 52 009.06), mediation (92 NAC 52 009.05), due process (92 NAC 52 009.07), and resolution (92 NAC 52
                009.08).
            </TD>
        </TR>
        <TR>
            <TD colspan="3" style="<?= $atnb ?>text-align: center;">Types of Services and Locations Discussed:</TD>
        </TR>
        <TR>
            <TD colspan="3" style="<?= $atn ?>">
                <?= $this->form->services_and_locations ?>
            </TD>
        </TR>
        <TR>
            <TD colspan="3" style="<?= $atn ?>">
                <?= $this->form->contact_for_questions ?>
            </TD>
        </TR>
    </table>
    <table class="formSectionHead" cellspacing="0" cellpadding="0">
        <tr>
            <td>Parent Signature</td>
        </tr>
    </table>
<?php if('print' == $this->mode) { ?>
    <table class="formInput" style="margin-top:1px;">
        <tr>
            <td width="100" valign="bottom" style="height:25px;white-space: nowrap;">Parent Signature:</td>
            <td width="225" valign="bottom" style="white-space: nowrap;">
                <?php
                if('t' == $this->form->signature_on_file->getValue()) {
                    echo 'Yes';
                    echo '<hr size="1" />';
                } else {
                    echo '<hr size="1" />';
                }
                ?></td>
            <td width="50" valign="bottom" align="right" style="height:25px;white-space: nowrap;">Date:</td>
            <td width="225" valign="bottom" align="left" style="white-space: nowrap;">
                <?php
                if(strlen($this->form->signature_on_file_date->getValue()) > 0) {
                    echo $this->form->signature_on_file_date->getValue();
                    echo '<hr size="1" />';
                } else {
                    echo '<hr size="1" />';
                }
                ?></td>
        </tr>
    </table>
<?php } else { ?>
    <table class="formInput" style="width:100%;">
        <tr>
            <td><?php echo $this->form->signature_on_file; ?></td>
        </tr>
        <tr>
            <td><?php echo $this->form->signature_on_file_date; ?></td>
        </tr>
    </table>
<?php } ?>