		
	<script type="text/javascript">
		//<!-- 

function startSpellCheck(){
    var myFrames = new Array();
    var counter = 0;
    $('iframe').each(function(){
        myFrames[counter] = $(this).attr('id');
        counter++;
    });

    doSpell({    
           ctrl: myFrames,
           lang: 'en_US',
           onFinish:onFinish
        });
}
onFinish = function(mSender){
	for(var i=0;i<mSender.length;i++){
		// updateInlineValueTextArea : textareaID, updateValue
		//updateInlineValueTest(mSender[i].id.replace("_iframe", ""), $('#'+mSender[i].id).contents().find('body').html());
	}
//	modified();
};
		//-->

	</script>	
	<div class="header">&nbsp;</div>
	<h1>WebSpellChecker for multiple text boxes</h1>
	<h3>Please enter your text into the boxes below and press the "Spell Check" button.</h3>
	<div class="container">
    	<table id="mailForm">
        	<tbody><tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor1" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        	<tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor2" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        	<tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor3" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        	<tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor4" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        	<tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor5" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        	<tr>
            	<th>Comments:</th>
            	<td style="border: 1px solid rgb(127, 157, 185); width: 600px;">
            		<iframe id="myEditor6" src="https://iepweb02dev.nebraskacloud.org/spellcheck/samples/editable_doc.html" style="width: 600px;" frameborder="0"></iframe>
				</td>
            </tr>
        </tbody></table>
	</div>
	<input value="Spell Check" onclick="startSpellCheck();" type="button">
	

