<div class="header" style="margin-bottom:50px">
    <h1>Header</h1>
    <div class="loginBox">
        <?php echo $this->loginForm; ?>
    </div>
    <!-- end loginBox -->
</div>
<!-- end header -->

<div class="navMain">
<div><a href="search/basicsearch">Basic Search</a></div>
<div><a href="search/advancedsearch">Advanced Search</a></div>
</div>
<!-- end navMain -->

<div class="contentMain">


Your sale has been completed.

An email copy of your receipt and download instructions was sent to the email address you supplied.<BR><BR>

To download your recently purchased files, please click <a href="profile">here</a>.
</div>
<!-- end content -->

<!--<div class="footer">-->
<!--<h3>Footer</h3>-->
<!--</div>-->
<!-- end footer -->
