<form name="searchFormHome" method="post">
<table>
	<tr>
		<td class="bt" style="padding-top: 10px;"><B>Login:</B></td>
	</tr>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->email;?></td>
	</tr>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->password;?></td>
	</tr>
	<tr>
		<td class="bts" style="padding-top: 10px;">I understand that
		information concerning children receiving special education services,
		personnel providing special education services, and other personally
		identifiable information which may come to my knowledge while
		accessing this information will be held in strictest confidence. I
		understand that access to this information is permitted only if it is
		pertinent to my work assignment. I further agree to abide by all
		requirements set forth in <a
			href="http://www.ed.gov/offices/OM/fpco/ferpa/index.html"
			target="_blank" class="underline"><span class="btsLBlue"
			style="text-decoration: underline;">The Family Educational Rights and
		Privacy Act</span></a> (FERPA) (20 U.S.C. &szlig; 1232g; 34 CFR Part
		99).</td>
	</tr>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->agree;?></td>
	</tr>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->submit;?></td>
	</tr>
</table>

</form>
