<tr class="<?php echo $this->class?>">
	<td class="cssCell" >
	    <?php echo $this->categoryName; ?>
		<?php echo $this->element->uncat_countKeywords; ?>
	</td>
	<td class="cssCell" colspan="1" >&nbsp;</td>
	<td class="cssCell"><?php echo $this->element->purchaseUncat; ?> Include with purchase</td>
	<td class="cssCell" colspan="4" >&nbsp;</td>
	<td class="cssCell"><?php echo $this->countKeywords; ?><?php echo $this->element->kwcount; ?></td>
</tr>
