<?php
$view = $this->element->page->getView();

echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_025; ?>
<?= $this->element->page; ?>
<table class="formTitleHead" cellspacing="0" cellpadding="0">
    <tr class="noprint">
        <td><?= $view->title ?></td>
    </tr>
</table>
<table class="formInput" style="padding-bottom: 10px;text-align: left">
    <tr><td width="50%"><?= $this->element->parent_names; ?></td>
        <td><?= $this->element->date_notice; ?></td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2">The parent of a child with a disability must be afforded the opportunity to
            participate in meetings with respect to the identification, evaluation, and educational
            placement of the child and the provision of FAPE to the child. Each
            district must provide notice consistent with 92 NAC 51-007.06A1 and 007.06B to ensure that
            parents of children with disabilities have the opportunity to participate in meetings
            described in 92 NAC 51-009.01A.</td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2">Lincoln Public Schools would like to schedule a meeting with you to complete
            the following actions in regard to your child:<br/>
        </td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2" class="printIndentCell">
            <?= $this->element->schedule_discuss_concerns ?>
            <?= $this->element->schedule_consider_referral ?>
            <?= $this->element->schedule_other ?>
        </td>
    </tr>
    <?php
    if('print'!=$view->mode || 1 == $this->element->schedule_other->getValue()) { ?>
    <tr>
        <td colspan="2">
            <?= $this->element->schedule_other_text ?>
        </td>
    </tr>
    <?php } ?>
    <tr>
        <td colspan="2" >The meeting has been scheduled for:</td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2">
            <table style="width: 100%">
                <tr>
                    <td class="printCellUnderline">
                        <?= $this->element->scheduled_date?>
                    </td>
                    <td class="printCellUnderline">
                        <?= $this->element->scheduled_time?>
                    </td>
                    <td class="printCellUnderline">
                        <?= $this->element->scheduled_place?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2">In addition to you, the parent, and your child (if appropriate), the following people will be in attendance at the meeting.</td>
    </tr>
    <tr class="printSpaceUnder">
        <td colspan="2">
            <table width="100%">
                <tr>
                    <td><?
                        echo $this->element->general_ed_teachers->getDescription();
                        $this->element->general_ed_teachers->removeDecorator('Description');
                        ?>
                    </td>
                    <td style="min-width:150px;"><?= $this->element->general_ed_teachers;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->special_ed_teachers->getDescription();
                        $this->element->special_ed_teachers->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->special_ed_teachers;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->school_district_rep->getDescription();
                        $this->element->school_district_rep->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->school_district_rep;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->individuals_to_explain_implications->getDescription();
                        $this->element->individuals_to_explain_implications->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->individuals_to_explain_implications;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->individuals_with_special_knowledge->getDescription();
                        $this->element->individuals_with_special_knowledge->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->individuals_with_special_knowledge;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->other_family_members->getDescription();
                        $this->element->other_family_members->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->other_family_members;?></td>
                </tr>
                <tr>
                    <td><?
                        echo $this->element->nonpublic_reps->getDescription();
                        $this->element->nonpublic_reps->removeDecorator('Description');
                        ?>
                    </td>
                    <td><?= $this->element->nonpublic_reps;?></td>
                </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td colspan="2"><strong>If the above date, time, or place is not agreeable to you and you would like to change the meeting,
            please contact</strong></td>
    </tr>
    <tr>
        <td colspan="2">
            <?=$this->element->meeting_contact_name;?> at <?=$this->element->meeting_contact_phone_or_email;?>
        </td>
    </tr>
</table>
