<?php
	$view = $this->element->page->getView(); 
    echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
	echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_007; ?>
<?= $this->element->page; ?>
    
<?php if('print' != $view->mode) { ?>
<table class="formTitleHead" cellspacing="0" cellpadding="0">
   <tr>
        <td>Notice and Consent for Initial Evaluation Continued</td>
    </tr>
</table>
<?php } ?>
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td><b>The district proposes to conduct the following components of the reevaluation:</b></td>
    </tr>
    <tr>
		<td>
	<blockquote><b><?php echo $this->element->academic_required; ?></b>
		<?php echo $this->element->academic; ?></blockquote>
		</td>
    </tr>
    <tr>
		<td>
	<blockquote><b><?php echo $this->element->intellectual_required; ?></b>
		<?php echo $this->element->intellectual; ?> </blockquote>
		</td>
    </tr>
    <tr>
		<td>
<blockquote><b><?php echo $this->element->perceptual_required; ?></b>
		<?php echo $this->element->perceptual; ?></blockquote>
		</td>
    </tr>
    <tr>
		<td>
	<blockquote><b><?php echo $this->element->social_required; ?></b>
		<?php echo $this->element->social; ?></blockquote> 
		</td>
    </tr>
    <tr>
		<td>
<blockquote><b><?php echo $this->element->speech_required; ?></b>
		<?php echo $this->element->speech; ?></blockquote>
		</td>
    </tr>
    <tr>
		<td>
<blockquote><b><?php echo $this->element->other_required; ?></b>
		<?php echo $this->element->other; ?></blockquote>
		</td>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td><i><b>
        Parents of children with disabilities have rights which are protected under the 
        procedural safeguards of the Individuals with Disabilities Act (IDEA). A copy of 
        your parental rights is enclosed. If you have any questions regarding this notice 
        or your rights you may contact:</i></b>
        </td>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td>
        <?php echo $this->element->contact_name; ?>
        </td>
        <td>
        <?php echo $this->element->contact_num; ?>
        </td>
    </tr>
    <? if($view->lps) { ?>
    <TR><td>Records for your child are no longer needed to provide educational services to
    your child when five (5) years has passed since the record was last created or revised
    and your child has moved to the next building level except records designated in Board
    policy as a permanent individual record, and is subject to destruction once that period is elapsed.
    </td></tr>
    <? } ?>
</table>

<?php echo $this->additionalResources(); ?>
