<?php 
    $view = $this->element->page->getView();
	echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
	echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_007; ?>
<?= $this->element->page; ?>

<?php if('print' != $view->mode) { ?>

<STYLE TYPE="text/css">
<!--
.indented
   {
   padding-left: 20pt;
   padding-right: 10pt;
   }
-->
</STYLE>


<table class="formTitleHead" cellspacing="0" cellpadding="0">
   <tr>
        <td>Notice and Consent for Reevaluation</td>
    </tr>
</table>
<?php } ?>
<table class="formInput" style="margin-top:1px;">  
   <tr>
        <td>
        <?php echo $this->element->date_notice; ?>
        </td>
    </tr>    
</table>
<br>
<table class="formInput">
    <tr>
        <td class="bgLight2">
        <strong><?php echo $view->db_form_data['student_data']['name_district']; ?></strong> proposes to conduct a multidisciplinary evaluation of your 
        child. The district proposes to evaluate your child because: </td>
    </tr><br>
   <tr>
        <td heighth ="50%"><b>
        1. Explanation of why the district proposes to reevaluate your child:</b>
       
     <blockquote><?php echo $this->element->explanation; ?></blockquote>
        </td>
    </tr>    
    <tr>
		<td>
		<b>	2. Any options the district considered:</b>
		<blockquote>	<?php echo $this->element->options; ?></blockquote>
		</td>
    </tr>
    <tr>
		<td>
		<b> 3. Reasons why the above options were rejected:</b>
		<blockquote><?php  echo $this->element->reasons; ?></blockquote>
		</td>
	</tr>
	<tr>
		<td>
		<b>	4. This proposal is based on the evaluation procedures, tests, 
            records, or reports described below:</b>
		<blockquote><?php echo $this->element->proposal; ?></blockquote>
		</td>
	</tr>
	<tr>
		<td>
		<b>5. Any other factors relevant to this proposal:</b>
		<blockquote><?php echo $this->element->other_factors; ?></blockquote>	
		</td>
	</tr>
</table>
