<html>

<!--  <link rel="stylesheet" href="https://mike-dev.aapnebraska.org/css/w3.css"> -->
<link href="/css/w3.css" media="screen" rel="stylesheet" type="text/css">
<body class="w3-container">
<center>

 <table border="0"> 
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    
                   
                  echo   $this->navigationSubmenu('Student'); 
                } ?>
            </td>
        </tr>
    </table><p><p><br><br>
     <!-- End of logo row -->
     
<style>
#srs_mainPane {
    top: 115px;
    border: none;
    overflow: visible;
    margin-left: 90px;
}
#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}

#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}    
</style>        
<?php // I dont thing this does much


                
$Stu_id= $this->studentId;
                
$Stu_id_county=$this->somedata[0]['id_county']; 
$Stu_id_district=$this->somedata[0]['id_district'];
$seed_id=$Stu_id;

 ?><div id=Heading><?php 
 
$cnt=count($this->schoolName);
for ($x=0;$x<$cnt;$x++){
 
   if($this->districtList[0]['id_school']==$this->schoolName[$x]['id_school']) {
        echo "<h2><center>".$this->schoolName[$x]['name_school']." ".$this->schoolName[$x]['id_district']." ".$this->schoolName[$x]['id_county']
             ." ".$this->schoolName[$x]['id_school']."</h2></center>";
           }
   } ?>
   
<br>
<select onChange="window.location.href=this.value">
<option value=''>Please Select A School</option>
<?php 
$cnt=count($this->schoolName);


for ($x=0;$x<$cnt;$x++){
?>

      
  <option value="<?php echo $this->url(array('controller'=>'staff','action'=>'team','id_county'=>$this->schoolName[$x]['id_county'],
                        'id_district'=>$this->schoolName[$x]['id_district'],
                       'id_school'=>$this->schoolName[$x]['id_school'],
                       'status'=>'true'));?>"><?php  echo $this->schoolName[$x]['name_school']; ?></option>
    
    
 
<?php  
} ?>

</select>
</div> 
    <br>
<div class="w3-col w3-border w3-round-xlarge w3-striped w3-light-blue w3-center" style="width:15%"><b>List of Students</b><p>
<!--   <div class="w3-col w3-border w3-round-xlarge w3-striped l2 w3-light-blue w3-center"><b></b><p>List of Students</b></p>
  -->
  <style>
  
 th {
   	text-align: left;
    font-size:0.70em;
    }
    
a:link {
    text-decoration: none;
}

a:visited {
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

a:active {
    text-decoration: underline;
}
 

   </style>
 
 
  <?php 
//  $all=$this->studentList;
  $all=$this->studentList;
  $x=0;
  $numberStu=count($all); 
  
 
  
  $x=0;
 
  
  
 ?>
 
 <table>
 <?php 
 
 // This loop printes the list of students on the  left side of the screen only from school x
 foreach($this->paginator2 as $pg2) {
    
     ?>
     <tr><th>
   <a href="https://iepweb02.esucc.org/staff/team/id_county/<?php echo $this->id_county?>/id_district/<?php echo $this->id_district?>/id_student/<?php echo $pg2['id_student']?>/id_personnel/<?php echo $this->user_id?>/id_school/<?php echo $pg2['id_school']?>">
      <?php echo $pg2['id_student']." ". $pg2['name_first']." ".$pg2['name_last'];?></a>
      </th></tr>
 
    <?php 
    
} ?>

<?php echo $this->paginationControl($this->paginator2,'sliding','sqlpaginator.phtml',array('route'=> 'staff/team'));
?>
</table>
</div>




<div class="w3-col  w3-center" style="width:5%"><p></div>

<div class="w3-col w3-lightblue w3-center w3-striped w3-border w3-border-red  w3-round-xlarge"style="width:40%">
 <form action ="https://iepweb02.esucc.org/staff/update/" method="post">
<table><tr>

<h3 class="w3-text-shadow w3-light-blue"> <i>Student:</i> <?php  echo $this->nameStudentFull ?></h3></tr>
<?php 

// This prints a list of staff members 
// TWo outer loops bellow.  Loop one prints the staff members belonging to certain student
//First outter loop
echo ('<table  class="w3-table w3-bordered w3-striped w3-border-green">');
 
    $incStaff=1;
    $staffCnt=count($this->districtList);
   // each person in the district in the privilege table
   foreach($this->districtList as $person) {    
       $checkv='';
       $checke='';
       $checkc='';
       $p['exists']="no";
       $stopLoop="no";
       $stat='';
       
       
    if($this->staffMemberRights!=NULL) {
// This first inner loop will see if the staff member has rights
        foreach($this->staffMemberRights as $personRights) {
           
        
           // this block checks to see if the entries in iep_team_members exist
           
           if( ($personRights['id_personnel']== $person['id_personnel'] && $stopLoop=="no")) {
                 $stat=$personRights['status'];
                $p['exists']='yes';
                $stopLoop="yes";
                 $checkc='';
                 $checke=''; 
                 $checkv='';
           // writevar($personRights['id_personnel'],'this is the persons id in the inner loop');
             
             if ((($personRights['flag_edit']== '1')) 
              && ($personRights['id_personnel']== $person['id_personnel'])) {
                   $checke="checked";
            }
            
              
             
             if ((($personRights['flag_view']== '1'))
                  && ($personRights['id_personnel']== $person['id_personnel'])) {
                      
                      $checkv="checked";
                  }
                  
             if ((($personRights['flag_create']== '1'))
                      && ($personRights['id_personnel']== $person['id_personnel'])) {
                  
                          $checkc="checked";
                      }
                        
                  
             }
                
       }  // end of the INNER loop
     
        $stopLoop='no';
        
             $fullName= ($person['id_personnel']."<b> ".$person['name_first']." ".$person['name_last']."</b> ".$person['class']." ".$person['name_district'].
                         " ".$person['id_school']);
           
        
             
         // if the person is found we print it out to the screen and then go back and get the next staff member.    
        if ($p['exists']=='yes'&& $stat=='Active'){
        //    writevar($fullName,'this is the fullname');
          ?>
      
             <th> <input type ="hidden" name="id_student "  value="<? echo  $this->id_student ?>">  <?php echo $fullName;?></th>
            
            
             <th>  <input type="checkbox" name="<?php echo("E_". $person['id_personnel'])?>" value="1" <?php echo $checke?>>edit</th>
             <th><input type="checkbox" name="<?php echo ("V_".$person['id_personnel'])?>" value="1"<?php echo $checkv?>>view</th>
             <th><input type="checkbox" name="<?php echo("C_". $person['id_personnel'])?>" value="1"<?php echo $checkc?>>create</th>
             <th> <input type ="hidden" name="<?php echo( $incStaff."_");?>id_personnel"  value="<? echo  $person['id_personnel']?>"></th>
             <th><input type="hidden" name=" <?php echo ("X_".$person['id_personnel'])?>"value=<?php echo $p['exists']?>></th></tr><p>
              
      
       
           
           
           
           
        
          
         
       <?php $incStaff=$incStaff+1;  }?>
       
      
       <?php 
     
         }
     }  // END OF OUTER FOREACH AS PERSON 
   
  ?>
  
 
  </table><table>
  <tr>Teachers not part of <?php echo $this->nameStudentFull;  ?>'s team</tr>
 
 <?php 
  $staffCnt=count($this->districtList);
  
  $countStaff=0;
  foreach($this->paginator as $person) 
  {    
      $checkv='';
      $checke='';
      $checkc='';
      
      $p['exists']="no";
      $stopLoop="no";
      $stat='';
      
      if($this->staffMemberRights!=NULL) {
          
      
      foreach($this->staffMemberRights as $personRights) {
          if( ($personRights['id_personnel']== $person['id_personnel'] && $stopLoop=="no")) {
               
              $p['exists']='yes';
              $stopLoop="yes";
              $checkc='';
              $checke='';
              $checkv='';
              $stat=$personRights['status'];
               
              if ((($personRights['flag_edit']== '1'))
                  && ($personRights['id_personnel']== $person['id_personnel'])) {
                      $checke="checked";
                  }    
                  if ((($personRights['flag_view']== '1'))
                      && ($personRights['id_personnel']== $person['id_personnel'])) {
                        $checkv="checked";
                      }
  
                      if ((($personRights['flag_create']== '1'))
                          && ($personRights['id_personnel']== $person['id_personnel'])) {
  
                              $checkc="checked";
                          }
          }
           
      }  // end of inner foreach personrights
      }
      $fullName= ($person['id_personnel']."<b> ".$person['name_first']." ".$person['name_last']."</b> ".$person['class']." ".
          $person['name_district']." ".$person['id_school']);

       if ($p['exists']=='no'|| $stat=='Removed') { ?>
         
             <tr>
          
            <th> <input type ="hidden" name="id_student "  value="<? echo  $Stu_id ?>">  <?php echo $fullName;?></th>
            
            
             <th>  <input type="checkbox" name="<?php echo("E_". $person['id_personnel'])?>" value="1" <?php echo $checke?>>edit</th>
            <th><input type="checkbox" name="<?php echo ("V_".$person['id_personnel'])?>" value="1"<?php echo $checkv?>>view</th>
            <th><input type="checkbox" name="<?php echo("C_". $person['id_personnel'])?>" value="1"<?php echo $checkc?>>create</th>
             <th> <input type ="hidden" name="<?php echo( $incStaff."_");?>id_personnel"  value="<? echo  $person['id_personnel']?>"></th>
            <th><input type="hidden" name=" <?php echo ("X_".$person['id_personnel'])?>"value=<?php echo $p['exists']?>></th></tr><p>
           
         
         <?php $incStaff=$incStaff+1; }?>
         
         <?php 
      
  } // end of the outter person for each
    ?>
    <center><?php echo $this->paginationControl($this->paginator,'sliding','sqlpaginator.phtml',array('route'=> 'staff/team'));
    
  
     
     ?>
     
     <?php $incStaff=$incStaff-1;?>
     </table>
    <input type="hidden" name="id_district" value ="<?php echo $this->id_district?>">
    <input type="hidden" name="id_county" value ="<?php echo $this->id_county?>">
    <input type="hidden" name="count" value =<?php echo $incStaff?>>
    <input type="hidden" name="id_student" value =<?php echo $Stu_id?>>
    <input type="hidden" name="id_personnel" value = <?php echo $this->id_user ?>>
    <input type="hidden" name="id_school" value = <?php echo $this->id_school ?>>
    </tr>
    <input type="submit" value="SAVE"><p>
   </form></tr>
   
   
  
  
   
   </table><br><p><br>
   </div>
  
  
      
        
      
          
    
   
  <!--  <link rel="stylesheet" href="https://mike-dev.aapnebraska.org/css/w3.css"> -->
<link href="/css/w3.css" media="screen" rel="stylesheet" type="text/css">
<body class="w3-container">
<center>


 