<?php $auth = Zend_Auth::getInstance(); ?>

<table border="0">   
        <!-- logo row -->
            <td>
                <?php if ($auth->hasIdentity()) { 
                echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php if ($auth->hasIdentity()) {
                  echo   $this->navigationSubmenu('Student'); 
                } ?>
            </td>
        </tr>
</table>
<style>
#srs_mainPane {
    top: 115px;
    border: none;
    overflow: visible;
    margin-left: 10px; 
}
#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}
#mainFooter{
	 height: 0px;
    padding-bottom: 0; 
	
}
#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}


.topMenu {
    position: relative;
    float: left;
    margin: 20px;
    margin-left: 0px;
}

.leftMenu {
    position: relative;
    width:28%;
    min-height: 300px;    
    float: left;
    margin: 2px;
    padding: 4px;
    border-radius: 6px 6px 6px 6px;
    -moz-border-radius: 6px 6px 6px 6px;
    -webkit-border-radius: 6px 6px 6px 6px;
    border: 1px solid #fa0303;
}

.rightMenu {
    position: relative;
    width:68%;
    min-height: 300px;
    float: left;
    margin: 2px;
    padding: 4px;    
    border-radius: 6px 6px 6px 6px;
    -moz-border-radius: 6px 6px 6px 6px;
    -webkit-border-radius: 6px 6px 6px 6px;
    border: 1px solid #fa0303;
}

.rightMenu select {
    position: relative;
    float: right;
}

#searchTable {
    display: none;
}

#cancelSearch {
    position: absolute;
    top: 41px;
    right: 10px;
    color: #a0a0a0;
    cursor: pointer;
}

.studentList tr {
    height: 24px;
}

.studentList th {
    margin: 2px;
    font-size: 14px;
    font-weight: 700;
    padding: 2px;
}

.studentList td {
    margin: 2px;
    padding: 6px;
}

.pagination {
    font-size: 13px;
    font-weight: 700;
    background: #efefef;
}

.tableHeader {
    height: 30px;
    background: #efefef;
    border-bottom: 1px solid #e0e0e0;
}


</style>

<?
    $all = $this->studentList;
    
    $x=0;
    $numberStu = count($all);
    $studentList = Array();
    $studentArray = "";
?>

<script type="text/javascript">
    $(document).ready(function () {
<?


    foreach($all as $key => $val) {
    	$studentList[] = [ $val['name_first'], $val['name_last'], $this->id_county, $this->id_district, $val['id_student'], $this->user_id, $val['id_school'] ];
	$studentArray .= ", [ '".addslashes($val['name_first'])."', '". addslashes($val['name_last'])."', '".$this->id_county."', '".$this->id_district."', '".$val['id_student']."', '".$this->user_id."', '".$val['id_school']."']";
    }
    $studentArray = substr($studentArray, 2);

?>
        var studentsList = [ <?=$studentArray?> ];

	$(document).on( "keyup", "#searchAlphabet", function() {
	    var searchAlphabet = $.trim($("#searchAlphabet").val());
	    var searchAlphabetLength = searchAlphabet.length;

	    if (searchAlphabet == "") {
		$("#searchAlphabet").val("");
    		$("#searchTable").html("");		
		$("#searchTable").hide();	        
		$("#originalTable").show();
	     } else if ( searchAlphabetLength > 0 && searchAlphabet != "") {
		$("#originalTable").hide();
		$("#searchTable").show();	        
		var i = 0;
		var color = "#FFFFFF";
		var finded = 0;
    		$("#searchTable").html("<table width='100%' id='findres' class='studentList'>")
        		$.each(studentsList, function(indx, val) {
			    color = (i % 2) ? "#FFFFFF" : "#F0F0F0";
			    i++;
			    if ((val[1].substr(0, searchAlphabetLength)).toLowerCase() == searchAlphabet.toLowerCase()) {
				finded++;
			        $("#findres").append('<tr bgcolor="' + color + '"><td><a href="/staff/team/id_county/' + val[2] + '/id_district/' + val[3] + '/id_student/' + val[4] + '/id_personnel/' + val[5] + '/id_school/' + val[6] + '">' + val[0] + ' ' + val[1] + '</a></td></tr>');
			    } 
			});

		if (finded == 0) $("#findres").append('<tr><td><center><br><br>No matches<br><br></center></td></tr>');
	    	$("#searchTable").append("</table>")
	     } 

    	    return false;
	});

	$(document).on( "click", "#cancelSearch", function() {
	    $("#searchAlphabet").val("");
	    $("#searchTable").html("");
	    $("#searchTable").hide();	        
	    $("#originalTable").show();
    	    return false;
	});


	$(document).on( "change", "#student_options", function() {
	    var url = $("#student_options").val();

	    var regExMark = new RegExp("\/IEP\/|\/MDT\/|\/IFSP\/|\/Progress Report\/", "ig"); 
	    if (url.match( regExMark )) { 
		url = "/student/get-most-recent/" + url;
	        $.ajax({
			type: 'POST',
	                dataType: 'json',
	                url: url,
    			success: function(response) {
        		    if (response['success'] == '1') {
                		window.location.href = response['url'];

	            	      } else {
	                	alert('The system was unable to locate the most recent form.');
			    }
			}		
		    });
    	    } else
		 window.location = url;

    	    return false;
	});

    });

</script>

<?
$Stu_id = $this->studentId;

$Stu_id_county=$this->somedata[0]['id_county']; 
$Stu_id_district=$this->somedata[0]['id_district'];
$seed_id=$Stu_id;
$cnt=count($this->schoolName);

$accessLevel = array( "1" => "System Admin", "2" => "District Manager", "3" => "Associate District Manager", "4" => "School Manager", "5" => "Associate School Manager",
		      "6" => "Case Manager", "7" => "School Staff", "8" => "Specialist", "9" =>  "Parent/Guardian", "10" => "Service Coordinator" );
?>

<select onChange="window.location.href=this.value" class="topMenu">
<option value=''>Please Select A School</option>
<?for ($x=0;$x<$cnt;$x++){?>
  <option value="<?php echo $this->url(array('controller'=>'staff','action'=>'team','id_county'=>$this->schoolName[$x]['id_county'],
                'id_district'=>$this->schoolName[$x]['id_district'], 'id_school'=>$this->schoolName[$x]['id_school'],
                'status'=>'true'));?>"<?if ($this->districtList[0]['id_school']==$this->schoolName[$x]['id_school']){?> selected<?}?>>
                <?=$this->schoolName[$x]['name_school']?></option>
<?}?>
</select>

<br><br>
<?
for ($x=0;$x<$cnt;$x++){
   if($this->districtList[0]['id_school']==$this->schoolName[$x]['id_school'])
        echo "<center><h1>".$this->schoolName[$x]['name_school']."</h1></center>";
}
?>
<br><br>



<div class="leftMenu">
<table class="studentList">
<tr><th class="tableHeader">List of Students</th></tr>
<tr><th>
<?php if ($this->allowView==true ){?>
    <input type="text" value="" style="width: 99%;" id="searchAlphabet">
   <?php }?> <div id="cancelSearch"><i class="fa fa-times"></i></div>
</th></tr>
</table>

<div id="originalTable">
<table class="studentList">
<?
$i = 1;
foreach($this->paginator2 as $pg2) {
    $cseMgr=$pg2['cm_first'].' '.$pg2['cm_last'];
    $color = ($i % 2) ? "#F0F0F0" : "#FFFFFF";
    $i++;
?>
<tr bgcolor="<?=$color?>"><td>
    <?php if($this->allowView==true ){
      ?>
    <a href="/staff/team/id_county/<?=$this->id_county?>/id_district/<?=$this->id_district?>/id_student/<?=$pg2['id_student']?>/id_personnel/<?=$this->user_id?>/id_school/<?=$pg2['id_school']?>"><font size="2pts"><?=$pg2['name_first']." ".$pg2['name_last']?></a>  Case Mgr: <?php echo $cseMgr?>       
    <?php }
    else {
     echo "<h2><b>".$pg2['name_last']."</b></h2>";   
    }
    ?>
</td></tr>
<?
}

?>
<tr><td class="pagination"><?php echo $this->paginationControl($this->paginator2,'sliding','sqlpaginator.phtml',array('route'=> 'staff/team'));?></td></tr>
</table>
</div>

<div id="searchTable">
    <center><i class="fa fa-spinner fa-pulse fa-2x fa-fw" style="margin: 20px auto;"></i></center>
</div>

</div>


<div class="rightMenu">
<form action ="/staff/update/" method="post">
<table class="studentList">





<style>
#student_options {
	float:left;
}
.tableHeader {
	float:center;
	font-size: 14px;
    font-weight: 700;
    padding: 2px;
}
.casemgr {
 margin: 2px;
    font-size: 14px;
    font-weight: 700;
    padding: 2px;
    color:green;	
</style>


<tr class="tableHeader"><td><center><h2>Student Team For <font color="blue"> <?=$this->nameStudentFull?></font></h2></td></center>
<td><?=$this->studentOptions($this->studentId, $this->id_district, $this->action)?></td>

<td >
<font class="casemgr"> Student's Case Manager: <?php echo $this->caseManager?>

</td>
</tr>





<?php 

    $incStaff=1;
    $staffCnt=count($this->districtList);
   // each person in the district in the privilege table
   
    
    // Mike added this 7-25-2017
      // Mike added this 8-4-2017 
         //if($this->allowView==true  && $this->initialList==true) it was
         // if($this->allowView==true) this renders nothing to the page at the top
         //when full name of the student is "Please Select a Student"
         
   if($this->allowView==true  && $this->initialList==true){
       
   
   foreach($this->districtList as $person) {    
       $checkv='';
       $checke='';
       $checkc='';
       $p['exists']="no";
       $stopLoop="no";
       $stat='';
       
       
    if($this->staffMemberRights!=NULL) {
// This first inner loop will see if the staff member has rights
        foreach($this->staffMemberRights as $personRights) {
           // this block checks to see if the entries in iep_team_members exist
 
           if( ($personRights['id_personnel']== $person['id_personnel'] && $stopLoop=="no")) {
                 $stat=$personRights['status'];
                $p['exists']='yes';
                $stopLoop="yes";
                 $checkc='';
                 $checke=''; 
                 $checkv='';
           // writevar($personRights['id_personnel'],'this is the persons id in the inner loop');
             
             if ((($personRights['flag_edit']== '1')) 
              && ($personRights['id_personnel']== $person['id_personnel'])) {
                   $checke="checked";
            }
             if ((($personRights['flag_view']== '1'))
                  && ($personRights['id_personnel']== $person['id_personnel'])) {
                      
                      $checkv="checked";
                  }
                  
             if ((($personRights['flag_create']== '1'))
                      && ($personRights['id_personnel']== $person['id_personnel'])) {
                  
                          $checkc="checked";
                      }
                        
                  
             }
                
       }  // end of the INNER loop
       
    
       
       $privileges=$_SESSION['user']['user']->privs;
      // $privileges=$this->privsUser;
       $disabled="disabled";
       
       
       foreach($privileges as $privs){
           if($privs['class']==1 && $privs['status']=='Active') $disabled=" ";
       
           if($privs['id_county']==$this->id_county && $privs['id_district']==$this->id_district
               && $privs['class']<=3 && $privs['status']=='Active' ){ $disabled=" "; }
                
               if($privs['id_county']==$this->id_county && $privs['id_district']==$this->id_district
                   && $privs['id_school']==$this->id_school && $privs['class']<=6 && $privs['status']=='Active' )
               {$disabled=" ";
               }
            
       }
       
       // Mike added this 8-4-2017 to make sure that we do not have
       // anybody just adding a student id outside the list.
       if($disabled==" " && $this->case_mgr==true) {
           $foundUnListedStudent=false;
           foreach($this->studentList as $pupils){
                
               if($pupils['id_student']==$this->idStudentFull) {
                   $foundUnListedStudent=true;
               }
               //    $this->_redirect('https://iep.unl.edu/srs.php?area=home&sub=home');
           }
          if($foundUnListedStudent==false)die();
       }
       
       
       
       
     
        $stopLoop='no';
    	    // $person['id_personnel'].
             $fullName= ("<b> ".$person['name_first']." ".$person['name_last']."</b> - ".$accessLevel[$person['class']]); //." ".$person['name_district']." ".$person['id_school']);
           
        
             
           // if the person is found we print it out to the screen and then go back and get the next staff member.    
           if ($p['exists']=='yes'&& $stat=='Active'){
           //    writevar($fullName,'this is the fullname');
           $color = ($incStaff % 2) ? "#F0F0F0" : "#FFFFFF";

      
          
           if($this->menuLink==true && $this->case_mgr==true){
            $disabled="disabled";
           }
           
         
           
           ?>
      
      
      
      
             <tr bgcolor="<?=$color?>">
		<td><input type="hidden" name="<?php echo ($incStaff."_");?>id_personnel" value="<?echo  $person['id_personnel']?>">
	    <input type="hidden" name="<?php echo ("X_".$person['id_personnel'])?>" value="<?php echo $p['exists']?>">
		   <font size="2pts"><?php echo $fullName;?></td>
		<td><input type="checkbox" <?php echo $disabled?> name="<?php echo("E_". $person['id_personnel'])?>" value="1" <?php echo $checke?>><font size="2pts">edit</td>
		<td><input type="checkbox" <?php echo $disabled?> name="<?php echo ("V_".$person['id_personnel'])?>" value="1" <?php echo $checkv?>><font size="2pts">view</td>
		<td><input type="checkbox" <?php echo $disabled?> name="<?php echo("C_". $person['id_personnel'])?>" value="1" <?php echo $checkc?>><font size="2pts">create</td>
	    </tr>
     
             <?php $incStaff=$incStaff+1; 
	   }
       
         }
     }  // END OF OUTER FOREACH AS PERSON 
   } // end of Mike add 7-25-2017
   
  ?>
  </table>

<br><br>

  <table class="studentList">
  <tr class="tableHeader"><th colspan="4"><center><h2>Teachers not part of <font color="blue"><?php echo $this->nameStudentFull;  ?>'s </font> team</center></h2></th></tr>
 
 <?php 
 if($this->allowView==false){
     $disabled="disabled";
 }
 
 $staffCnt=count($this->districtList);
  
  $countStaff=0;
  foreach($this->paginator as $person) 
  {    
      $checkv='';
      $checke='';
      $checkc='';
      
      $p['exists']="no";
      $stopLoop="no";
      $stat='';
      
      if($this->staffMemberRights!=NULL) {
          
      
      foreach($this->staffMemberRights as $personRights) {
          if( ($personRights['id_personnel']== $person['id_personnel'] && $stopLoop=="no")) {
               
              $p['exists']='yes';
              $stopLoop="yes";
              $checkc='';
              $checke='';
              $checkv='';
              $stat=$personRights['status'];
               
              if ((($personRights['flag_edit']== '1'))
                  && ($personRights['id_personnel']== $person['id_personnel'])) {
                      $checke="checked";
                  }    
                  if ((($personRights['flag_view']== '1'))
                      && ($personRights['id_personnel']== $person['id_personnel'])) {
                        $checkv="checked";
                      }
  
                      if ((($personRights['flag_create']== '1'))
                          && ($personRights['id_personnel']== $person['id_personnel'])) {
  
                              $checkc="checked";
                          }
          }
           
      }  // end of inner foreach personrights
      }
      // $person['id_personnel'].
      $fullName= ("<b> ".$person['name_first']." ".$person['name_last']."</b> - ".$accessLevel[$person['class']]); //." ".$person['name_district']." ".$person['id_school']);

      // Mike added the Inactive 8-25-2017 because it was just Inactive in the db.
      // it was not showing users that were removed from iep and not iepweb02 because
      // it was marking status in the db table as Inactive.
       if ($p['exists']=='no'|| $stat=='Removed'|| $stat=='Inactive') {
           
       
     // Mike added this 8-25-2017  need to check      
           if($stat=='Inactive') $checke='';


      $color = ($incStaff % 2) ? "#F0F0F0" : "#FFFFFF";

      if($this->menuLink==true) $disabled="disabled";
     
      ?>
         
             <tr bgcolor="<?=$color?>">
		<td>
		    <input type="hidden" name="<?php echo( $incStaff."_");?>id_personnel" value="<? echo  $person['id_personnel']?>">
        	    <input type="hidden"  name="<?php echo ("X_".$person['id_personnel'])?>" value=<?php echo $p['exists']?>>    
		   <font size="2pts"> <?php echo $fullName;?></font></td>
		<td><input type="checkbox"<?php echo $disabled?>  name="<?php echo("E_". $person['id_personnel'])?>" value="1" <?php echo $checke?>><font size="2pts">edit</font></td>
		<td><input type="checkbox" <?php echo $disabled?> name="<?php echo ("V_".$person['id_personnel'])?>" value="1"<?php echo $checkv?>><font size="2pts">view</font></td>
		<td><input type="checkbox" <?php echo $disabled?> name="<?php echo("C_". $person['id_personnel'])?>" value="1"<?php echo $checkc?>><font size="2pts">create</font></td>
            </tr>
          <?
          $incStaff=$incStaff+1; 
        }
  } // end of the outter person for each

    $color = ($incStaff % 2) ? "#FFFFFF" :'#F0F0F0';
    ?>
    <tr><td colspan="4" style="padding: 6px 0;">
        <input type="hidden" name="id_district" value = "<?php echo $this->id_district?>">
        <input type="hidden" name="id_county" value = "<?php echo $this->id_county?>">
        <input type="hidden" name="count" value="<?php echo $incStaff?>">
        <input type="hidden" name="id_student" value="<?php echo $Stu_id?>">
        <input type="hidden" name="id_personnel" value = "<?php echo $this->id_user ?>">
	<input type="hidden" name="id_school" value = "<?php echo $this->id_school ?>">
        <input type="submit" <?php echo $disabled?>  value="SAVE" style="float: right; margin-right: 30px;">
    </td></tr>
    <tr><td class="pagination" colspan="4">
       <?php 
         echo $this->paginationControl($this->paginator,'sliding','sqlpaginator.phtml',array('route'=> 'staff/team'));
         $incStaff=$incStaff-1; ?>
    </td></tr>   
  
   </table>
  </form>


</div>
      
<br><p><br>
