<?
//$this->headLink()->appendStylesheet('/css/_layout.css', 'screen');

/*
 * Mike made these additions 3-20-17 so that we can redirect the 
 * /scrtips/helpers/NavigationSubmenu.php links pending the user we are 
 * working with instead of using the session variables.  
 */
$first_n=rtrim($this->userInfo['name_first']);
$last_n=rtrim($this->userInfo['name_last']);
$staff_id=$this->userInfo['id_personnel'];
$district_id=$this->userInfo['id_district'];
$county_id=$this->userInfo['id_county']; 
$school_id=$this->userinfo['id_school'];

$completeName=$first_n." ".$last_n;

$linkPrivileges='https://iepweb02.esucc.org/staff/addotherstaff/id_personnel/'.$staff_id.'/name_last/'.$last_n.'/name_first/'
           .$first_n.'/id_district/'.$district_id.'/id_county/'.$county_id.'/id/0/';
$linkDistrictSchool='https://iepweb02.esucc.org/personnelm/indexb/id_county/'.$county_id.
                     '/id_district/'.$district_id.'/id_school/'.$school_id.'/status/true';

$linkPWchange='https://iepweb02.esucc.org/passwordchange/changepassword/id_personnel/'.$staff_id . '/name_first/' . $first_n . '/name_last/' . $last_n;

//$linkPWchange='https://iepweb02.esucc.org/passwordchange/index2/id_personnel/'.$staff_id.
               '/name_first/'.$first_n.'/name_last/'.$last_n;
// End of Mike add
 ?>
<script type="text/javascript">

$("document").ready(function() {
	
	$(".openWindow.mike").attr("rel","<?php  echo $linkPrivileges?>")
	.attr("href","<?php echo "#"?>").attr("title","<?php echo $completeName?>");
// Mike added this part 3-19-2017
	$(".mike2").attr("href","<?php echo $linkDistrictSchool?>").attr("title","<?php echo $completeName?>");

	$(".pwchange2") 
	.attr("rel","<?php echo $linkPWchange?>")
	.attr("href","<?php echo "#"?>")
	.attr("title","<?php echo $completeName?>")
	.html("<font color=\"green\"><i><b>Change Passwords for  <?php echo $completeName  ?></font></i></b>");
// end of mike add 
	
})

</script>
<script type="text/javascript">
    $(function () {

		$('#submit').click(function() {

			if ($('#status').val() == 'Removed' || $('#status').val() == 'Inactive') {
				if ($('#status-error')) {
					$('#status-error').remove();
				}
				
				var hasActivePrivileges = true;
				$.ajax({
					async: false,
	                type: 'POST',
	                dataType: 'json',
	                url: '/personnel/has-active-privileges/id_personnel/' + $('#id_personnel').val(),
	                success: function (json) {
	                	hasActivePrivileges = json.response;
	                },
	                error: function () {
	                    console.debug('error');
	                }
	            });
				if (true == hasActivePrivileges) {
	                $('#status-colorme').append('<span id="status-error" style="color:#c00;"> &nbsp; You cannot delete or inactivate a personnel record that still has active privileges.</span>');
	                return false;
	            } else if ($('#status').val() == 'Removed') {
		            	var confirmed = confirm("Warning: Removing Personnel cannot be undone, Are you sure that you wish to permanently delete this personnel record?");
						if (confirmed)
							return true;
						else
							return false;
	            } else {
		            return true;
	            }
			}
		});
        
        $('#send_login_info').click(function () {
            $('#send-login-info-message').html('Preparing an email with your login info...');
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/personnel/send-login-info/id_personnel/' + $('#id_personnel').val(),
                success: function (json) {
                    if (true == json.response) {
                        $('#send-login-info-message').html('A message with your login info has been sent to your email (' + json.email + ').');
                    } else {
                        $('#send-login-info-message').html('There was an error sending your login info.');
                    }
                },
                error: function () {
                    console.debug('error');
                }
            });
        });
    });
</script>

<script type="text/javascript">
    $(document).ready(function() {

      $(document).on("click", ".openWindow", function () { 
        var title = $(this).attr("title");
        var url = $(this).attr("rel"); 
        if (url != ""){
         $("#dialog").load( url,
           function() {
            $("#dialog").dialog({  show: { effect: "fade", duration: 500 }, 
                                          hide: {effect: "fade", duration: 500}, 
                                          width: 550, height: 400, resizable : true, 
                                          title: title, modal: true, beforeClose: function(event, ui) { $("#dialog").html(""); } } );
                                 });
        }
        return false;

      });

      $(document).on("click", ".pwchange2", function () { 
          var title = $(this).attr("title");
          var url = $(this).attr("rel"); 
       //   console.log(url);
          if (url != ""){
           $("#dialog2").load( url,
             function() {
              $("#dialog2").dialog({  show: { effect: "fade", duration: 500 }, 
                                            hide: {effect: "fade", duration: 500}, 
                                            width: 550, height: 400, resizable : true, 
                                            title: title, modal: true, beforeClose: function(event, ui) { $("#dialog").html(""); } } );
                                   });
          }
          return false;

        });

    $(document).on("keyup change", "#id_district", function () {
   	  $("#schoolload").html('<i class="fa fa-spinner fa-pulse"></i>');
       $("#GrandPriv").hide();
       $("#id_school").empty().hide();
       $("#label_school").show();
       
       var data_sel = $("#id_district").val().split("|");
       var data_var = Array;
	   console.log(data_sel);
       data_var["id_county"] = data_sel[0];
       data_var["id_district"] = data_sel[1];
      
       console.log(data_sel[0]);
       console.log(data_sel[1]);
       
       $.ajax({
          type       : "GET",
          url        : "/staff/addotherstaffschoollist/",
          crossDomain: true,
          cache      : false,
          data       : data_var,
          dataType   : "json",
          success    : function(response) {
            if (response.length > 0){
              $("#schoolload").html('');
              $("#id_school").append('<option value="">Choose...</option>');
              $.each(response, function (key, val) { $("#id_school").append("<option value='"+val.id_school+"'>"+val.name_school+"</option>"); 
                                                       console.log(key);console.log(val); });
	      $("#id_school").show();
	      $("#label_school").show();
	    } else {
	      $("#label_school").hide();
	      $("#id_school").empty().hide();
              $("#schoolload").html('');
	    }
          }
        });

      return false;
    });
    $(document).on("keyup change", "#id_school", function () {
	var NameSchool = $("#id_school :selected").text();
	    $('#SchoolName').html(NameSchool);
        $("#GrandPriv").show();

      return false;
    });

    $(document).on("click", ".StaffSave", function () {

       var data_var = Array;
       data_var = {};
       var res = "";

       $("#StaffForm input, #StaffForm select").each( function(index, element) {
	      if ($(element).attr("name") == "id_district") {
		    var value = $(element).val().split("|");
	            data_var[encodeURIComponent("id_county")] = encodeURIComponent(value[0]);
                    data_var[encodeURIComponent("id_district")] = encodeURIComponent(value[1]);
  	       } else if ($(element).attr('type') == "radio") {
                    if ($(element).prop('checked')) data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
	       } else 
                    data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
       });


      $.ajax({
          type       : "POST",
          url        : "/staff/addotherstaffsave",
          crossDomain: true,
          cache      : false,
          data       : data_var,
          dataType   : "html",
          success    : function(response) {
	    $('#StaffDiv').html(response);
          }
      });
      return false;
    });
 });

    
</script>
<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/privilege_list.css', 'screen');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/privilege_detail.css', 'screen');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/personnel-privileges.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/personnel-student-chart-template.js');
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/personnel-privilege-actions.js');

?>
<table border="0">
    <!-- logo row -->
    <?php $auth = Zend_Auth::getInstance(); ?>
    <tr>
        <td colspan="2">
            <?php if ($auth->hasIdentity()) {
                echo $this->navigationTopTabs('simple');// This most certainly are the navigation tabs at the top Mike june 9th
            } ?>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <?php if ($auth->hasIdentity()) {
              
              echo $this->navigationSubmenu('Personnel'); //This is the personnel list and New Privilege Mike June 9th
            } ?>
            
             <?php $fullName=$this->userInfo['name_first'].' '.$this->userInfo['name_last']?>
   
   
   
            
        </td>
    </tr>
</table>
<style>
.blueHeadline2 {
    border:1px solid #AAAAAA;
    font-size:14px;
    background-color:#2F4F4F;
    color:#fff;
    padding:2px 10px;
    margin:0px 0px;
}    
  </style>

<div class="clearfix sectionContainer">
 <?php if($this->form_personnel !='') {?>
    <h3 class="blueHeadline2"><?= $this->viewOnly ? 'View' : 'Edit' ?> Personnel</h3>
<?php }?>
    <div class="sectionContainer">
        <div class="message"><? if (isset($this->message)) {
             echo $this->message;
            } ?></div>
            
  <?php 
  
  if($this->changePassword == true){
  $fullName=$this->userInfo['name_first'].' '.$this->userInfo['name_last']?>
   
   
   <?php $staffmembers=$this->userInfo; ?>
   
 
  
    
   
    <?php } echo $this->form_personnel; ?> <?php // this is the actuall form  Mike June 9th 2016?>

<style>
.blueHeadline {
    border:1px solid #AAAAAA;
    font-size:14px;
    background-color:#3366cc;
    color:#fff;
    padding:7px 10px;
    margin:2px 5px;
}    
  </style>
   
    
   
   
    <h3 class="blueHeadline">Privilege List for  <?php echo $fullName; ?>
  
    </h3>
    
    
   

    <div>
        <div class="message"><? if (isset($this->message)) {
                echo $this->message;
            } ?></div>
        <dl>
            <dd id="add-privilege"></dd>
        </dl>
        <dl class="list-container">
            <dd>
                <fieldset>
                    <div class="wrapperDiv">
                        <dl class="zend_form">
                            <span class="column_name_county">County</span>
                            <span class="column_name_district">District</span>
                            <span class="column_name_school">School</span>
                            <span class="column_role">Role</span>
                            <span class="column_status">Status</span>
                            <span class="column_links">Actions</span>
                        </dl>
                    </div>
                </fieldset>
            </dd>
            <?php foreach ($this->privileges as $key => $priv) { ?>
                <dd id="personnel_privilege<?= $priv['id_privileges'] ?>">
                    <fieldset>
                        <div class="wrapperDiv">
                            <dl class="zend_form">
                                <span class="column_name_county"><?= $priv['name_county']; ?>&nbsp;</span>
                                <span class="column_name_district"><?= $priv['name_district']; ?>&nbsp;</span>
                                <span class="column_name_school"><?= $priv['name_school']; ?>&nbsp;</span>
                                <span class="column_role"><?= $priv['class_description']; ?>&nbsp;</span>
                                <span class="column_status"><?= $priv['status']; ?>&nbsp;</span>
                        <span class="column_links">
                            <?
                            if($priv['access']) {
                                switch($priv['status']) {
                                    case 'Active':
                                        echo '<a class="btn-update-privilege" href="/personnel/update-privilege/id_privileges/'.$priv['id_privileges'].'/status/Inactive">Inactivate</a> | ';
                                        echo '<a class="btn-delete-privilege" href="/personnel/delete-privilege/id_privileges/'.$priv['id_privileges'].'">Remove</a>';
                                        break;
                                    case 'Inactive':
                                        echo '<a class="btn-update-privilege" href="/personnel/update-privilege/id_privileges/'.$priv['id_privileges'].'/status/Active">Activate</a> | ';
                                        echo '<a class="btn-delete-privilege" href="/personnel/delete-privilege/id_privileges/'.$priv['id_privileges'].'">Remove</a>';
                                        break;
                                }
                            }
                            ?>
                        </span>
                            </dl>
                        </div>
                    </fieldset>
                </dd>
            <?php } ?>
        </dl>
    </div>

    <? if(count($this->templates)) { ?>
    <div>
        <h3 class="blueHeadline">Template List</h3>
        <dl class="list-container">
            <dd>
                <fieldset>
                    <div class="wrapperDiv">
                        <dl class="zend_form">
                            <span class="column_goal_desc">Goal Description</span>
                            <span class="column_chart_type">Chart Type</span>
                            <span class="column_links">Actions</span>
                        </dl>
                    </div>
                </fieldset>
            </dd>
            <?php foreach ($this->templates as $key => $template) { ?>
                <dd id="student_chart_template_<?= $template['id_student_chart_template'] ?>">
                    <fieldset>
                        <div class="wrapperDiv">
                            <dl class="zend_form">
                                <span class="column_goal_desc"><?= $template['goal_desc']; ?>&nbsp;</span>
                                <span class="column_chart_type"><?= $template['chart_type']; ?>&nbsp;</span>
                            <span class="column_links">
                                <a class="btn-remove-student-chart-template"
                                   href="/personnel/delete-student-chart-template/id_student_chart_template/<?= $template['id_student_chart_template']; ?>">Remove</a>
                            </span>
                            </dl>
                        </div>
                    </fieldset>
                </dd>
            <?php } ?>
        </dl>
    </div>
    <? } else { ?>
        <div>
            <h3 class="blueHeadline">No Templates</h3>
        </div>
    <? } ?>
</div>
<div id="dialog">
</div>
<div id="dialog2">
</div>


