<style>

.flex-container {
	display:-webkit-flex;
	display: -ms-flexbox;
	display: flex;
	margin: 1em 0;
	flex-flow: row wrap-reverse;
}  	

.tableStaff {
    width: 100%;
    min-width: 800px;
}

.tableStaff tbody tr:hover td {
	background: #F4A460;
}

.tableStaff th{
    padding: 4px;
    font-size: 12px;
    font-weight: 700;
    text-align: left;
    border-bottom: 1px dotted #a0a0a0;
}	

.tableStaff td {
    padding: 4px;
    border-bottom: 1px solid #f0f0f0;
    font-size: 12px;
}	


</style>
<?if (!isset($this->area) || $this->area == ""){?>

<?php
$first_n=$_SESSION['user']['user']->user['name_first'];
$last_n=$_SESSION['user']['user']->user['name_last'];
$staff_id=$_SESSION['user']['user']->user['id_personnel'];
$district_id=$_SESSION['user']['user']->user['id_district'];
$county_id=$_SESSION['user']['user']->user['id_county'];
$school_id=$_SESSION['user']['user']->user['id_school'];

$completeName=$first_n." ".$last_n;
$linkPrivileges='/staff/addotherstaff/id_personnel/'.$staff_id.'/name_last/'.$last_n.'/name_first/'
    .$first_n.'/id_district/'.$district_id.'/id_county/'.$county_id.'/id/0/';
?>

<script type="text/javascript">
  $(document).ready(function () {

   $(".mike2").attr("href","<?php echo ""?>");
   $(".mike2").text("");
   $(".openWindow.mike").attr("rel","<?php echo $linkPrivileges?>").attr("href","<?php echo "#"?>").attr("title","<?php echo $completeName?>");

   $(document).on("click", ".openWindow", function () { 
	 	  var title = $(this).attr("title");
	     var url = $(this).attr("rel"); 
	     if (url != ""){
	      $("#dialog").load( url,
	        function() {
	         $("#dialog").dialog({  show: { effect: "fade", duration: 500 }, 
	                                       hide: {effect: "fade", duration: 500}, 
	                                       width: 550, height: 400, resizable : true, 
	                                       title: title, modal: true, beforeClose: function(event, ui) { $("#dialog").html(""); } } );
	                              });
	     }
	     return false;

	   });

	 $(document).on("keyup change", "#id_district", function () {
		  $("#schoolload").html('<i class="fa fa-spinner fa-pulse"></i>');
	    $("#GrandPriv").hide();
	    $("#id_school").empty().hide();
	    $("#label_school").show();

	    var data_sel = $("#id_district").val().split("|");
	    var data_var = Array;
		
	    data_var["id_county"] = data_sel[0];
	    data_var["id_district"] = data_sel[1];
	    console.log(data_sel[0]);
	    console.log(data_sel[1]);
	    $.ajax({
	       type       : "GET",
	       url        : "/staff/addotherstaffschoollist/",
	       crossDomain: true,
	       cache      : false,
	       data       : data_var,
	       dataType   : "json",
	       success    : function(response) {
	         if (response.length > 0){
	           $("#schoolload").html('');
	           $("#id_school").append('<option value="">Choose...</option>');
	           $.each(response, function (key, val) { $("#id_school").append("<option value='"+val.id_school+"'>"+val.name_school+"</option>"); 
	                                                    console.log(key);console.log(val); });
		      $("#id_school").show();
		      $("#label_school").show();
		    } else {
		      $("#label_school").hide();
		      $("#id_school").empty().hide();
	           $("#schoolload").html('');
		    }
	       }
	     });

	   return false;
	 });
	 
	 $(document).on("keyup change", "#id_school", function () {
		var NameSchool = $("#id_school :selected").text();
		$('#SchoolName').html(NameSchool);
	     $("#GrandPriv").show();

	   return false;
	 });

	 $(document).on("click", ".StaffSave", function () {

	    var data_var = Array;
	    data_var = {};
	    var res = "";

	    $("#StaffForm input, #StaffForm select").each( function(index, element) {
		      if ($(element).attr("name") == "id_district") {
			    var value = $(element).val().split("|");
		            data_var[encodeURIComponent("id_county")] = encodeURIComponent(value[0]);
	                 data_var[encodeURIComponent("id_district")] = encodeURIComponent(value[1]);
		       } else if ($(element).attr('type') == "radio") {
	                 if ($(element).prop('checked')) data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
		       } else 
	                 data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
	    });


	   $.ajax({
	       type       : "POST",
	       url        : "/staff/addotherstaffsave",
	       crossDomain: true,
	       cache      : false,
	       data       : data_var,
	       dataType   : "html",
	       success    : function(response) {
		    $('#StaffDiv').html(response);
	       }
	   });
	   return false;
	 });

   
 // This was already there for the screen refresh   
    $(document).on("change keyup", "#sortby", function () {
      var url = $(this).val() + "/area/right/";
      if (url != ""){ 
       $.ajax({
          type       : "POST",
          url        : url,
          crossDomain: true,
          cache      : false,
          dataType   : "html",
	  beforeSend: function() {
              $(".loading").clone().css("position", "absolute").css("top", "0px").css("border", "0px").css("bottom", "0px").css("left", "0px").css("margin-top", "100px").show().appendTo(".flex2");

          },
          success    : function(response) {
	    $(".flex2").html(response);
          }
        });
       }
       return false;
      });

    $(document).on("click", ".PersonnelSave", function () {
       var data_var = Array;
       data_var = {};

       $("#PersonnelForm input").each( function(index, element) {
	  if (($(element).attr("type") == "radio" && $(element).is(":checked")) || $(element).attr("type") != "radio") data_var[$(element).attr('name')] = $(element).val();
       });

       $.ajax({
          type       : "POST",
          url        : "/personnelm/updatePrivs/area/right/",
          crossDomain: true,
          cache      : false,
	  data       : data_var,
          dataType   : "html",
	  beforeSend: function() {
              $(".loading").clone().css("position", "absolute").css("top", "0px").css("border", "0px").css("bottom", "0px").css("left", "0px").css("margin-top", "100px").show().appendTo(".flex2");
          },
          success    : function(response) { 
	     $(".flex2").load('/personnelm/indexb/id_county/'+data_var['id_county']+'/id_district/'+data_var['id_district']+'/id_school/'+data_var['id_school']+'/status/'+data_var['status']+'/area/right/');
	  }
        });
       return false;
    });
  });
</script>

<?php if ($this->message) { ?>
    <div class="message"><?= $this->message ?></div>
<?php  }?> 

    <table border="0"> 
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?> 
            <td colspan="2">
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                   echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('personnel');
                } ?>
            </td>
        </tr>
    </table>

<div class="box flex1" style="float: left;">

<h1><b><center>Status of Staff at Other Schools</center></b></h1><br><p>
<table>
<?php 
 foreach($this->schools as $schools){ ?>
<tr><td><strong><?php echo $schools['name_school']?></strong></td></tr>
<tr><td style="padding: 2px;">
 <select id="sortby">
   <option value="/personnelm/indexb/id_county/<?=$schools['id_county']?>/id_district/<?=$schools['id_district']?>/id_school/<?=$schools['id_school']?>/status/true"> Select Staff Status</option>
   <option value="/personnelm/indexb/id_county/<?=$schools['id_county']?>/id_district/<?=$schools['id_district']?>/id_school/<?=$schools['id_school']?>/status/true"> Active Staff</option>
  <option value="/personnelm/indexb/id_county/<?=$schools['id_county']?>/id_district/<?=$schools['id_district']?>/id_school/<?=$schools['id_school']?>/status/false"> Inactive Staff</option>
  <option value="/personnelm/indexb/id_county/<?=$schools['id_county']?>/id_district/<?=$schools['id_district']?>/id_school/<?=$schools['id_school']?>/status/removed"> Removed Staff</option>
 </select>
</td></tr>
<?}?>
</table>
<?}?>

</div><div class="box flex2" style="float: left;">

<?if ($this->area == "right" || $this->area == "" || !isset($this->area)){?>
<? $x=0; ?>
<h1><b><center>List of Staff at <?php echo $this->schoolName?> School</center></b></h1><br>

<form id="PersonnelForm">
<table class="tableStaff">
<tr><th>NAME</th><?/*<th>District Name</th>*/?><th>Class Value</th><?/*<th>School Id</th>*/?><th>Status</th></tr>

<?php foreach($this->staffListb as $staff)
  {
      $fname=$staff['name_first'];
      $lname=$staff['name_last'];
      $fullName=$fname." ".$lname;
      $id=$staff['id_personnel'];
      $t=$staff['class'];
      $name='';
      switch ($t){
          case 2: $name='District Manager';
          break;
          case 3: $name='Associate District Manager';
          break;
          case 4: $name='School Manager';
          break;
          case 5: $name='Assistant School Manager';
          break;
          case 6: $name='Case Manager';
          break;
          case 7: $name='School Staff';
          break;
          case 8: $name='Specialist';
          break;
          case 10: $name='Service Coordinator';
          break;
      }
    if($staff['status']!='') {
     $status=$staff['status'];
     $checkA='';
     $checkI='';
     $checkR='';
     
      switch($status){
          case 'Active': $checkA="checked";
          break;
          case 'Inactive':$checkI="checked";
          break;
          case 'Removed' :$checkR="checked";
          break;
          
      }
     
     
     
     ?>
      
     <tr>
        <td><a href=/personnelm/edit/id_personnel/<?php echo $staff['id_personnel']?>><?php echo $fullName?></a></td>
<?/*        <td><?php echo $staff['name_district']?></td>*/?>
        <td><?php echo $name?>
            <input type ="hidden" name="<?php echo ("ID_".$x)?>"value="<? echo $staff['id_personnel']?>">
            <input type ="hidden" name="<?php echo ("CLASS_".$x)?>"value="<? echo $staff['class']?>">
<?/*        <td><?=$staff['id_school']?></td>*/?>
        <td><input type ="radio" name="<?php echo ("S_".$x)?>"value="Active"<?php echo $checkA?>>Active
            <input type ="radio" name="<?php echo ("S_".$x)?>"value="Inactive"<?php echo $checkI?>>Inactive
            <input type ="radio" name="<?php echo ("S_".$x)?>"value="Removed"<?php echo $checkR?>>Removed
        </td>
     </tr>  

  <?php 
    $x=$x+1;
    }
  }
   ?>
  
    </tr> 
</table>

<input type = "hidden" name="id_county" value="<?php echo $this->countyId?>">
<input type = "hidden" name="count" value="<?=$x-1?>">
<input type = "hidden" name="id_district" value="<?php echo $this->districtId?>">
<input type = "hidden" name="id_school" value="<?php echo $this->schoolId?>">
<input type = "hidden" name="name_district" value="<?php echo $this->schoolName?>">
<input type = "hidden" name="status" value="<?php echo $this->status?>">
<?if ($x != 0){?><div style="float: right; margin: 20px;"><button class="ui-button ui-widget ui-corner-all PersonnelSave" style="padding: 2px 5px; margin: 10px; margin-right: 30px;">  Save  </button></div><?}?>
</form>
<?}?>
</div>

<div id="dialog"></div>
