
<?php if ($this->message) { ?>
    <div class="message"><?= $this->message ?></div> 
<?php  }?> 
<?php 
$first_n=$_SESSION['user']['user']->user['name_first'];
$last_n=$_SESSION['user']['user']->user['name_last'];
$staff_id=$_SESSION['user']['user']->user['id_personnel'];
$district_id=$_SESSION['user']['user']->user['id_district'];
$county_id=$_SESSION['user']['user']->user['id_county'];
$school_id=$_SESSION['user']['user']->user['id_school'];

$completeName=$first_n." ".$last_n;
$linkPrivileges='https://iepweb02.esucc.org/staff/addotherstaff/id_personnel/'.$staff_id.'/name_last/'.$last_n.'/name_first/'
    .$first_n.'/id_district/'.$district_id.'/id_county/'.$county_id.'/id/0/';
?>


<script type="text/javascript">
    $(document).ready(function() {
  $('#mainFooter').text("");
 // Tooltip
    	$('.tooltip').mouseover(function(e) {
    		
    		// data type - text
    		if ( $(this).attr('data-tip-type') == 'text' ){
    			$('#tooltip_container').html( $(this).attr('data-tip-source') );
    		}
    		
    		// data type - html
    		if ( $(this).attr('data-tip-type') == 'html' ){
    			var elementToGet = '#' + $(this).attr('data-tip-source');
    		//	var elementToGet2 = '#' + $(this).attr('data-tip-source2');
    			
    			var newHTML = $(elementToGet).html();
    			$('#tooltip_container').html( newHTML );

    		//	var newHTML2 = $(elementToGet).html();
    		//	$('#tooltip_container').html( newHTML2 );
    		}
    		$('#tooltip_container').css({'display':'block','opacity':0}).animate({opacity:1},250);
    	}).mouseout(function() {
    		$('#tooltip_container').animate({opacity:0},250, function(){
    			$('#tooltip_container').css('display','none')
    		});
    	});


   // End ToolTip     
        
    
   $(".openWindow.mike").attr("rel","<?php echo $linkPrivileges?>").attr("href","<?php echo "#"?>").attr("title","<?php echo $completeName?>");
	$(".mike2").text("");
	
	         

      $(document).on("click", ".openWindow", function () { 
    	  var title = $(this).attr("title");
        var url = $(this).attr("rel"); 
        if (url != ""){
         $("#dialog").load( url,
           function() {
            $("#dialog").dialog({  show: { effect: "fade", duration: 500 }, 
                                          hide: {effect: "fade", duration: 500}, 
                                          width: 550, height: 400, resizable : true, 
                                          title: title, modal: true, beforeClose: function(event, ui) { $("#dialog").html(""); } } );
                                 });
        }
        return false;

      });

    $(document).on("keyup change", "#id_district", function () {
   	  $("#schoolload").html('<i class="fa fa-spinner fa-pulse"></i>');
       $("#GrandPriv").hide();
       $("#id_school").empty().hide();
       $("#label_school").show();

       var data_sel = $("#id_district").val().split("|");
       var data_var = Array;
	
       data_var["id_county"] = data_sel[0];
       data_var["id_district"] = data_sel[1];
       console.log(data_sel[0]);
       console.log(data_sel[1]);
       $.ajax({
          type       : "GET",
          url        : "/staff/addotherstaffschoollist/",
          crossDomain: true,
          cache      : false,
          data       : data_var,
          dataType   : "json",
          success    : function(response) {
            if (response.length > 0){
              $
              ("#schoolload").html('');
              $("#id_school").append('<option value="">Choose...</option>');
              $.each(response, function (key, val) { $("#id_school").append("<option value='"+val.id_school+"'>"+val.name_school+"</option>"); 
                                                       console.log(key);console.log(val); });
	      $("#id_school").show();
	      $("#label_school").show();
	    } else {
	      $("#label_school").hide();
	      $("#id_school").empty().hide();
              $("#schoolload").html('');
	    }
          }
        });

      return false;
    });
    
    $(document).on("keyup change", "#id_school", function () {
	var NameSchool = $("#id_school :selected").text();
	$('#SchoolName').html(NameSchool);
        $("#GrandPriv").show();

      return false;
    });

    $(document).on("click", ".StaffSave", function () {

       var data_var = Array;
       data_var = {};
       var res = "";

       $("#StaffForm input, #StaffForm select").each( function(index, element) {
	      if ($(element).attr("name") == "id_district") {
		    var value = $(element).val().split("|");
	            data_var[encodeURIComponent("id_county")] = encodeURIComponent(value[0]);
                    data_var[encodeURIComponent("id_district")] = encodeURIComponent(value[1]);
  	       } else if ($(element).attr('type') == "radio") {
                    if ($(element).prop('checked')) data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
	       } else 
                    data_var[encodeURIComponent($(element).attr("name"))] = encodeURIComponent($(element).val());
       });


      $.ajax({
          type       : "POST",
          url        : "/staff/addotherstaffsave",
          crossDomain: true,
          cache      : false,
          data       : data_var,
          dataType   : "html",
          success    : function(response) {
	    $('#StaffDiv').html(response);
          }
      });
      return false;
    });
 });
</script>

<style>
#srs_mainPane {
    top: 115px;
    border: none;
    overflow: visible;
    margin-left: 10px; 
}
#srs_left .subBar_top {
    /*background:url(../images_srs/b_sbar_bg_top.jpg) no-repeat -8px top; */
    height: 0px;
    padding-bottom: 0; 
}
#mainFooter{
	 height: 0px;
    padding-bottom: 0; 
	
}
#srs_left .subBar_btm {
    /* background:url(../images_srs/b_sbar_bg_btm.jpg) no-repeat -8px top; */
    height: 0px; 
}
#leftTop {
    /*background:url(../images_srs/c_left_bg_top.png) no-repeat right top;*/
    height: 2px;
    padding: 0;
}	

#srs_left {
    position: fixed;
    top: 41px;
    left: 0;
    margin: 0;
    padding: 0;
    width: 40px;
    overflow: visible;
    font-size: 1em;
    color: #FFF;
    border: none;
}

#tooltip_container {
	color: black;
	position: absolute;
	display: none;
	padding: 20px;
	max-width: 400px; /* need i.e. rule */
	background-color:gainsboro;
	-webkit-border-radius: 12px;
	-moz-border-radius: 12px;
	border-radius: 12px;
}

.tooltip-source-html { display: none; }
</style>
    <table border="0"> 
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?> 
            <td colspan="2">
                <?php if ($auth->hasIdentity()) { // writevar($auth->getInstance(),'this is the identity of the person \n');
                   echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                   echo $this->navigationSubmenu('personnel');
                } ?>
            </td>
        </tr>
    </table>
   <br> 
<select class="tooltip" data-tip-type="html" data-tip-source="tooltip-sidebar" onChange="window.location.href=this.value">
<option  value=''>Please Select A District</option>



<?php 

foreach ($this->privileges as $privilege)
{
    $privilege['id_school']='001';
    if($privilege['name_district'])
    { 
        if(($privilege['class']==2 || $privilege['class']==2 )&& $privilege['status']=='Active'){    
              $privilege['id_school']='001';
        }

         ?>  

   <option value="<?php echo $this->url(array('controller'=>'personnelm','action'=>'indexb','id_county'=>$privilege['id_county'],
                        'id_district'=>$privilege['id_district'],
                       'id_school'=>$privilege['id_school'],
                       'status'=>'true'));?>"><?=$privilege['name_district'];?></option>       
            
<?php      
    }
}?>

</select>
<div id="dialog">
</div>

<div id="tooltip_container">districts </div>
			<div class="tooltip-source-html">
				<div id="tooltip-sidebar">
					<img src="/images/logo_small.gif" style="float:left;">
					Activate,Inactivate or Remove Staff from Schools.					
					<div class="clear-all"></div>
				</div>
				
				<div id="tooltip-sidebar2">
					<img src="/images/logo_small.gif" style="float:left;">
					Change your Password with this link.					
					<div class="clear-all"></div>
				</div>
				
				<div id="tooltip-sidebar3">
					<img src="/images/logo_small.gif" style="float:left;">
					Grant Yourself New Privileges.				
					<div class="clear-all"></div>
				</div>
			</div>

<br>
<br>
<br>
<br>
<br>
<br>

      