<form action="/form001/changepage" id="myform" method="post">
	<?php
		include_once('../application/views/scripts/formEditHeader.phtml');
		echo $this->form->getSubForm('student_data');
		
		echo $this->form;
		
		// this element is used by the changepage action
		echo $this->formHidden('mode', 'edit', array('ignore'=>true)); 
		echo $this->formHidden('form_number', '001', array('ignore'=>true));
        echo $this->formHidden('id_student', $this->db_form_data['id_student'], array('ignore'=>true));
        include_once('../application/views/scripts/formEditFooter.phtml');
	?>
</form>
<?php if(0) { ?>
<div id="programmatic2">This div will become an auto-expanding editor.</div>
<button
        id="create2"
        onclick="new dijit.Editor({height: '', extraPlugins: ['dijit._editor.plugins.AlwaysShowToolbar']}, dojo.byId('programmatic2')); dojo.query('#create2').orphan();">
create expanding editor
</button>



<BR /><BR /><BR /><BR />
<?php } ?>
