<?php 
    $view = $this->element->page->getView();
	echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
	echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_001; ?>
<?= $this->element->page; ?>

<?php if('print' != $view->mode) { ?>
<table class="formTitleHead" cellspacing="0" cellpadding="0">
   <tr>
        <td><?php echo $this->translate('Notice and Consent for Initial Evaluation Continued'); ?></td>
    </tr>
</table>
<?php } ?>
<table class="formInput" style="margin-top:1px;">     
    <tr>
		<td class="printBoldLabel"><?php echo $this->translate('Following is a description of the components of the multidisciplinary evaluation which the district proposes to conduct'); ?>:
		<br/>
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->academic_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/>
		<?php echo $this->element->academic; ?>
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->intellectual_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/>
		<?php echo $this->element->intellectual; ?> 
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->perceptual_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/>
		<?php echo $this->element->perceptual; ?>
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->social_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/>
		<?php echo $this->element->social; ?> 
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->speech_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/>
		<?php echo $this->element->speech; ?>
		</td>
    </tr>
    <tr>
		<td>
		<?php echo $this->element->other_required; ?>
		<?php echo $this->translate('Multidisciplinary Evaluation Description'); ?>:<br/> 
		<?php echo $this->element->other; ?>
		</td>
    </tr>
</table> 
<table class="formInput" style="margin-top:1px;">
	<tr>
		<td colspan="2">
		<?php echo $this->translate('Parents of children with disabilities'); ?>:
		</td>
	</tr>
	<tr>
		<td style="text-align:center;">
			<?php echo $this->element->contact_name; ?>
        </td>
        <td style="text-align:center;">
			<?php echo $this->element->contact_num; ?>
		</td>
	</tr>
</table>
<? if($view->lps) {?>
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td colspan="2">
            <?php echo $this->translate('Records provided'); ?>:
        </td>
    </tr>
</table>
<? } ?>
<?php echo $this->additionalResources('formTitleHead', 'printBoldLabeWithBorder'); ?>
