<?php
    $view = $this->element->page->getView();
    echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
    echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_001; ?>
<?= $this->element->page; ?>
<table class="formDesc" style="width:100%; height:40px;">
    <tr>
        <td>
        <strong><?php echo $view->db_form_data['student_data']['name_district']; ?></strong> <?php echo $this->translate('proposes to conduct a multidisciplinary evaluation of your child. The district proposes to evaluate your child because'); ?>: </td>
    </tr>
</table>
<?php if('print' != $view->mode) { ?>
<table class="formTitleHead" cellspacing="0" cellpadding="0">
    <tr>
        <td><?php echo $this->translate('Notice and Consent for Initial Evaluation'); ?></td>
    </tr>
</table>
<?php } ?>
<table class="formInput">     
    <tr class="noprint">
        <td>
            <?php echo $this->element->date_notice; ?>
        </td>
    </tr>
    <tr>
        <td>1. <?php echo $this->translate('Explanation of why the district proposes to evaluate your child'); ?>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->explanation; ?>  
    	</td>
    </tr>
</table>
<table class="formInput">
    <tr>
        <td>2. <?php echo $this->translate('Any options the district considered'); ?>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->options; ?>  
    	</td>
    </tr>
</table>
<table class="formInput">
    <tr>
        <td>3. <?php echo $this->translate('Reasons why the above options were rejected'); ?>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->rejected_reasons; ?>  
    	</td>
    </tr>
</table>
<table class="formInput">
    <tr>
        <td>4. <?php echo $this->translate('This proposal is based on the evaluation procedures, tests, records, or reports described below'); ?>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->proposal; ?>  
    	</td>
    </tr>
</table>
<table class="formInput">
    <tr>
        <td>5. <?php echo $this->translate('Any other factors relevant to this proposal'); ?>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->other_factors; //<div id="other_factors-colorme" class="colorme errored"> ?>
    		
            <?php //</div> ?>  
    	</td>
    </tr>
</table>
<table class="formInput">
    <tr>
        <td>6. <?php echo $this->translate('The estimated amount of time for completing the multidisciplinary evaluation and making the verification decision is'); ?> <span class="noprint">(<?php echo $this->translate('Not to exceed 45 school days'); ?>')</span>:</td>
    </tr>
    <tr>
    	<td>
    		<?php echo $this->element->amount_time; ?>  
    	</td>
    </tr>
</table>
		
