<div>Error List</div>
<div>
	<ul>
		<li><B>List now sorts by timestamp_created on first load.</B></li>
		<li><B>Search now searches on most fields..</B></li>
	</ul></div>

<?php if (isset($this->results)) { ?>
  <?php if (count($this->results) < 1) { ?>
    
      <div>No results matched your search</div>

  <?php } else { ?>
      <div><?= count($this->results).' results' ?></div>
      <table border="1">
      <tr>
          <td>URL</td>
          <td>&nbsp;</td>
<!--           <td>&nbsp;</td> -->
      </tr>
      <?php foreach ($this->results as $k => $r) { 
      
      	$error_text = $r['err'];
      	?>
          <tr>
              <td><?= $r['fl'] ?></td>
              <td><?
			      if(is_array($error_text)) {
			      	App_Debug::dump($error_text);	
			      } else {
			      	echo $error_text;
			      }
              
              ?></td>
<!--               <td> -->
<!--                 <div> -->
                    <a href="<?php echo $this->url(array(
//                     'controller' => 'esu',
//                     'action' => 'view',
//                     'id' => $r['form_number'],
                    ));?>">View</a>
<!--                 </div> -->
<!--               </td> -->
          </tr>
      <?php } ?>
      </table>
  <?php } ?>
<?php } ?>

<ul>

</ul>

<script type="text/javascript">
	var archiveTable;
	$(document).ready(function() {
		try{

			console.debug('load datatables');
			
			// datatable - list of errors
			archiveTable = $('#myarchivedatagrid').dataTable({
				"aoColumnDefs": [
				                 { "asSorting": [ "desc" ], "aTargets": [ 0 ] },
				               ],
				"bJQueryUI":true,
				"sPaginationType":"full_numbers",
		        "bProcessing": true,
		        "bServerSide": true,
		        "sAjaxSource": '/errorlog/get-js-err-log',
		        "fnServerData": function( sUrl, aoData, fnCallback ) {
		            $.ajax( {
		                "url": sUrl,
		                "data": aoData,
		                "success": fnCallback,
		                "dataType": "json",
		                "cache": false
		            } );
		        }
			});
			
			/* 
			 * Add change handler to the school menu
			 * will fire because triggerHandler("change") is applied on id_school 
			*/		
			$("#id_school").change(function() {
				$('#myarchivedatagrid').dataTable().fnDraw();
			});
		} catch(err) {
			console.debug('JAVASCRIPT ERROR: There has been an error trying to initialize the datatable.');
		}

	});
	
</script>

<table id="mainDisplay" border="1">
<tr style="background:grey;">
	<td></td>
</tr>
<tr>
	<td style="width:250px;">
		<table id="myarchivedatagrid" class="display">
		<thead>
			<tr>
				<th style="width:50px;">Created At</th>
				<th style="width:50px;">User ID</th>
				<th style="width:50px;">User Name</th>
				<th style="width:20px;">OS</th>
				<th style="width:20px;">Browser</th>
				<th style="width:20px;">Version</th>
				<th style="width:370px;">Erroring Url</th>
<!-- 				<th style="width:50px;">Document</th> -->
<!-- 				<th style="width:50px;">form_key</th> -->
				<th style="width:*;">Error Text</th>
				<th style="width:450px;">Erroring File</th>
				<th style="width:10px;">Line</th>
<!-- 				<th style="width:50px;">page_number</th> -->
<!-- 				<th style="width:50px;">student_id</th> -->
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
	</td>
</tr>
</table>
