<div>Error List</div>

<?php if (isset($this->results)) { ?>
  <?php if (count($this->results) < 1) { ?>
    
      <div>No results matched your search</div>

  <?php } else { ?>
      <div><?= count($this->results).' results' ?></div>
      <table border="1">
      <tr>
          <td>ESU Name</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
      </tr>
      <?php foreach ($this->results as $k => $r) { 
      
      	$error_text = unserialize($r['error_text']);
      	?>
          <tr>
              <td><?= $r['error_code'] ?></td>
              <td><?
			      if(is_array($error_text)) {
			      	App_Debug::dump($error_text);	
			      } else {
			      	echo $error_text;
			      }
              
              ?></td>
              <td>
                <div>
                    <a href="<?php echo $this->url(array(
                    'controller' => 'esu',
                    'action' => 'view',
                    'id' => $r['id_neb_esu'],
                    ));?>">View</a>
                </div>
              </td>
          </tr>
      <?php } ?>
      </table>
  <?php } ?>
<?php } ?>

<ul>

</ul>
