<?php if ($this->message) { ?>
    <div class="message"><?= $this->message ?></div>
<?php } ?>
<form action="/login/dochangepassword" method="post">
  <input type="hidden" name="email_address" value="<?= $this->email ?>" />
  <input type="hidden" name="token" value="<?= $this->token ?>" />
  <table>
     <tr><td>new password:</td><td><input type="password" name="new_password" /></td></tr>
     <tr><td>confirm password:</td><td><input type="password" name="confirm_password" /></td></tr>
     <tr><td>&nbsp;</td><td><input type="submit" value="change" /></td></tr>
  </table>
</form>