<form action="/login/choose" id="myform" method="post">

<table>
	<tr>
		<td class="bt">Welcome to the Nebraska School Districts Student Record
		System (SRS).<br />
		<br />
		Please choose one of the following options:</td>
	</tr>
</table>
<table>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->login_type;?></td>
	</tr>
	<tr>
		<td class="bt" style="padding-top: 10px;"><?=$this->element->submit;?></td>
	</tr>
</table>

</form>
