<link href="/css/w3.css" media="screen" rel="stylesheet" type="text/css">
<?php
$this->title = "Edit Districts";
$this->headTitle($this->title);
?>


<script type="text/javascript">
    $(document).ready(function() {
      $('#srs_mainPane').css('margin-left', "10px");
    });
</script>
<?php if ($this->message) { ?>
    <div class="message"><?= $this->message ?></div>
<?php } ?>

    <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('home');
                } ?>
            </td>
        </tr>
    </table>


    <table style=";" align="left" border="0">
        <tr>
            <td colspan="2" class="btsBig" align="center"><b>Welcome to the newer SRS home page.</b><br><br>
            </td>
        </tr>
        <tr>
            <td align="center" valign="top">
                <table border="0" style="width:450px;">
                    <?
                    echo "<tr><td colspan=\"2\" class=\"btbRed\" >";
                    // ADDED MESSAGE FOR NEW PRIVILAGE 030324-JL
                    // ===========================================
                    if(isset($option) && $option == 4) echo "To apply for a new privilege, select Edit Profile, then New Privilege.";
                    // ===========================================
                    echo "</tr></TD>";
                    ?>
                    <tr class="bgDark"><td align="center" nowrap="nowrap" style="height:19; width:10px;" colspan="2" class="menuTextBig"><B>Announcement Center</B></td><tr>
                    <tr class="bgLGrey">
                        <td align="center" nowrap="nowrap" style="height:19; width:1px;"><a href="/home/message-center" class="menuTextLinkBig" style="text-decoration:underline;"  >View Message Archive</a></td>
                        <td align="center" nowrap="nowrap" style="height:19; width:1px;"><a href="/home/message-center" class="menuTextLinkBig" style="text-decoration:underline;"  >Search Message Archive</a></td>
                    </tr>
                    <tr class="btGrey"><td colspan="2" class="bts">Messages below were created in the last week or are required to stay posted. Click 'View Message Archive' to see all messages. Click 'Search Message Archive' to search all messages. </td></tr>
                    <tr class="btGrey"><td colspan="2" class="bts"><img src='images/line_grey.gif' height=3 width='50%'></td></tr>
                    <tr>
                        <?
                        if (isset($numRows) && $numRows) {
                            for ($i = 0; $i < $numRows; $i++) {
                                $arrData = pg_fetch_array($result, $i);
                                if ($arrData['msg_type'] == "Warning") {
                                    $cssClass = "btsbRed";
                                } else {
                                    $cssClass = "bts";
                                }
                                if($arrData['msg_type'] == "Announcement") {
                                    $viewLink = " | <a href=\"srs.php?&area=home&sub=announcements&msgID=".$arrData['id_messages']."\"";
                                    $viewLink .= windowStatus('View this announcement');
                                    $viewLink .= ">View</a>";
                                } else {
                                    $viewLink = "&nbsp;";
                                }
                                echo "<tr><td class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j]>" . htmlEncode($arrData['msg_type']) . "</td><td class=\"$cssClass\" align=\"right\">".htmlEncode($arrData['create_date']).$viewLink."</tr>\n";
                                echo "<tr><td class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j] colspan=\"2\">\t" . htmlEncode($arrData['msg_title']) . "</td></tr>\n";
                                if($arrData['msg_type'] == "Warning") {
                                    echo "<TR><td colspan=\"3\" class=\"$cssClass\" style=\"padding-left:{$padding}px;\"$arrNowrap[$j] >" . htmlEncode($arrData['message_text']) . "</td></TR>\n";
                                }
                                echo "<tr>\n<td colspan=\"" . (count($arrFieldLabels) + 1) . "\"><img src='images/line_grey.gif' height=1 width='100%'></td>\n</tr>\n";
                            }
                        }
                        ?>
                </table>
            </td>
        </tr>
        <tr>
            <td align="center" colspan="2" class="btsBig"><BR><BR><i>This site is best viewed with a browser resolution of 1024x768 or greater.</i>
            </td>
        </tr>
    </table>

<?php // Mike Added 11-15-2016 to prevent spoofing the url

if($this->rights!='yes'){
    
echo"<center><h1>GO AWAY YOU HAVE NO RIGHTS FOR THIS PAGE</h1></center";
}
else 
{
    ?>
<u><h2><center>District Settings</center></h2></u>
 <style>

input {
	font-weight:bold;
	font-size: 0.85em;
	font-weight: bold;
	font-size:0.85em;
	color:darkbrown;
}
	input[type=text] {
    width: 60%;
   
}


#DistrictDemographics  {
	float:left;
    width:550px;
	height:820px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-weight:bold;
	font-size:0.85em;
	background-color:#DCE3E6;
	 border: 4px solid darkgreen;
	
}

#OptionalFeatures {
   
    width:450px;
	height:700px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-weight:bold;
	font-size:0.85em;
	 border: 2px solid darkgreen;
    background-color:#DCE3E6;
   
}
	
	#DistrictSettings {
    width:450px;
	
    float:left;
	height: 820px; 
    padding:10px;
	color:darkgreen;
	font-size:0.85em;
	font-weight:bold;
	border: 4px solid darkgreen;
		background-color:#DCE3E6;
}
 


#IepSummaryFormA {
	
    
    width:450px;
	height: 820px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-size:0.85em;
	font-weight:bold;
	color:green;
	border: 4px solid darkgreen;
	background-color:#DCE3E6;
    
}

#Transition {
    width:450px;
	height:450px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-size:0.85em;
	font-weight:bold;
	border: 4px solid darkgreen;
	background-color:#DCE3E6;
}

#Services {
    width:450px;
	height:450px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-size:0.95em;
	font-weight:bold;
	border: 4px solid darkgreen;
	background-color:#DCE3E6;
}

#Services2{
    width:450px;
	height:250px;
    float:left;
    padding:10px;
	color:darkgreen;
	font-size:0.85em;
	font-weight:bold;
	border: 4px solid darkgreen;
	background-color:#DCE3E6;
}

</style>

<?php

//echo "<table>";
// for($x=1;$x< $this->staffCount;$x++) { 
//    echo "<tr><td>";
// echo $this->districtStaff[$x]['email_address']; echo "</td>";
  //  echo "</tr>";
//} 
//echo "</table>";

echo $this->current_date_and_time;
?>


 
<?php 
//echo $this->noDecorators
echo $this->form;

?>

<br><br><p>

<script>

//var legends = document.getElementsByTagName('legend');
var demoList =  document.getElementById('fieldset-DIST').getElementsByTagName("legend");
var demoListLegend ="Demographics to Change";
var demoListText = "Note: you cannot change the District ID in this section. Contact Wade Furhling or Dawn Dewitt for further assistance";

var distSetting = document.getElementById('fieldset-DistrictSettings').getElementsByTagName("legend");
var distSettingLegend = "District Settings";
var distSettingText = "There will soon be a full blown calendar here.  "

var optionalFeatures =  document.getElementById('fieldset-OPTIONAL_FEATURES').getElementsByTagName("legend");
var optionalFeaturesLegend ="Optional Features";
var optionalFeaturesText = " As an official School District Manager for the Public Schools , you are aware that the optional features available within the Nebraska Student Records System (SRS) are neither required by state statutes, rules or federal regulations nor are necessary to meet the standards set forth in the Individuals with Disabilities Act (IDEA). Furthermore, I relieve the SRS from any responsibility associated with the use of the optional features. I recognize that, due to the individualized nature of these features (a result of their local school district development), the SRS is unable to provide support for these features.";


optionalFeatures[0].onmouseover =function()  {mouseOver(optionalFeatures,optionalFeaturesText)};
optionalFeatures[0].onmouseout = function () {mouseOver(optionalFeatures,optionalFeaturesLegend)};
	
distSetting[0].onmouseover =function()  {mouseOver(distSetting,distSettingText)};  
distSetting[0].onmouseout = function () {mouseOut(distSetting,distSettingLegend)};

demoList[0].onmouseover =function()  {mouseOver(demoList,demoListText)};  
demoList[0].onmouseout = function () {mouseOut(demoList,demoListLegend)};



//demographics[0].onmouseover = function() {mouseOver()};

//var DistDemographics = document.getAttributeByText("District Demographics To Change").tagName;).onmouseover = function() {mouseOver()};
//document.getElementById("DistrictDemographics").onmouseout = function() {mouseOut()};
//document.getElementById("fieldset-DIST").onmouseover = function() {popup()};

function mouseOver(list,thetext) {
/* var form_object =  document.getElementById("DistrictDemographics").form;
var form_elements = form_object.elements; // all elements of the form containing that obj_id
form_elements[0].style.color =  "red"; */

	list[0].style.color = "lightgray";
	list[0].innerHTML = thetext;
	
	

	//document.getElementById("DistrictDemographics").style.color = "brown";

//popup();
}

function mouseOut(list,description) {
list[0].style.color = "white";
list[0].innerHTML = description;


}

console.log("This is a node of type: ", demoList.nodeType);
console.log("Inner HTML: ", demoList.innerHTML);
console.log("Child nodes: ", demoList.length);
console.log(demoList[0]);
</script>
<br><br>

<?php } //this will end the rights?>






















