<?php 
    echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
    echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
?>
<?= $this->element->id_form_015; ?>
<?= $this->element->page; ?>
<?php $view = $this->element->page->getView(); ?>
    
  <table class="formTitleHead" cellpadding="0" cellspacing="0" style="margin-bottom:1px;">
    <tr>
      <td>Notice and Consent for Initial Evaluation Continued</td>
    </tr>
  </table>
  <table class="formInput" style="margin-top:1px;">
    <tr>
      <td style="width:635px">Following is a description of the components of the multidisciplinary evaluation which the district proposes to conduct:</td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Adaptive Development</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->academic; ?></td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Cognitive</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->intellectual; ?></td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Physical Development (Including Vision and Hearing)</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->perceptual; ?></td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Social and Emotional Development</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->social; ?></td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Speech and Language (Communication) Development</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->speech; ?></td>
    </tr>
    <tr>
      <td style="white-space: nowrap;"><strong><em>Other</em></strong><br>
      Multidisciplinary Evaluation Description:</td>
    </tr>
    <tr>
      <td>
      <?php echo $this->element->other; ?></td>
    </tr>
  </table>
<table class="formInput" style="margin-top:1px;">
    <tr>
    	<td>
    	<p>If your child is determined eligible for EDN services, a child assessment will be conducted to identify your child's unique strengths and needs in all areas of development and the early intervention services appropriate to meet those needs. Consent is required prior to completing your child's assessment. The assessment of your child must include:</p>
    	<ul style="list-style:none;">
    		<li>(a) a review of the results of the evaluation, if conducted;</li>
    		<li>(b) observations of your child; and</li>
    		<li>(c) the identification of your child's needs in each of the developmental areas within the context of your family's routines and activities.</li>
    	</ul>
    	</td>
    </tr>
</table>
  <table class="formInput" style="margin-top:1px;">
    <tr>
      <td colspan="6">Parents of children with a suspected disability have protection under the procedural safeguards of the Individuals with Disabilities Education Act (IDEA). A copy of these "<?php if ('print' != $view->mode) { ?><a target="_blank" href="http://iepweb02.esucc.org/pdf/PARENTSRIGHTS.pdf"><?php } ?>Parental Rights in Special Education<?php if ('print' != $view->mode) { ?></a><?php } ?>," as well as, a copy of <?php if ('print' != $view->mode) { ?><a target="_blank" href="http://iepweb02.esucc.org/pdf/NDE-Rule51-Sec.009.11.pdf"><?php } ?>92 NAC 51-009.11-92 NAC 51-009.11C10<?php if ('print' != $view->mode) { ?></a><?php } ?>, and <?php if ('print' != $view->mode) { ?><a target="_blank" href="http://iepweb02.esucc.org/pdf/CLEANRule55_2012.pdf"><?php } ?>Rule 55<?php if ('print' != $view->mode) { ?></a><?php } ?>, which is the procedure for filing complaints and requests for due process hearings is provided with this notice.
You should carefully read the information and, if you have questions regarding your rights, you may contact:</td>
    </tr>
    <tr align="center">
      <td nowrap="nowrap"><?php echo $this->element->contact_name; ?></td>
      <td nowrap="nowrap"><?php echo $this->element->contact_num; ?></td>
    </tr>
  </table>
  <table class="formSectionHead" cellpadding="0" cellspacing="0" style="margin-bottom:1px;">
    <tr>
      <td>Additional Resources</td>
    </tr>
  </table>
  <table class="formInput" style="margin-top:1px;">
    <tr>
      <td style="width:635px">You may contact any of the following resources to help you understand the federal and state laws for educating children with disabilities and parental rights granted by those laws. An explanation of your rights will be provided at no cost by any of the following organizations:</td>
    </tr>
    <tr>
      <td>
        <table class="formInput">
          <tr>
            <td colspan="2">Nebraska Department of Education Regional Offices:</td>
          </tr>
          <tr>
            <td>&nbsp;&nbsp;&nbsp;&nbsp;Lincoln Office</td>
            <td>(402) 471-2471</td>
          </tr>
          <tr>
            <td>&nbsp;&nbsp;&nbsp;&nbsp;Omaha Office</td>
            <td>(402) 595-2177</td>
          </tr>
          <tr>
            <td>&nbsp;&nbsp;&nbsp;&nbsp;Scottsbluff Office</td>
            <td>(308) 632-1349</td>
          </tr>
          <tr>
            <td>&nbsp;&nbsp;&nbsp;&nbsp;Hotline for Disability Services</td>
            <td>(800) 742-7594</td>
          </tr>
          <tr>
            <td>Nebraska Parent Training Center</td>
            <td>(800) 284-8520 or (402) 346-0525</td>
          </tr>
          <tr>
            <td>Nebraska Advocacy Services</td>
            <td>(800) 422-6691 or (402) 474-3183</td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
