<?php
function writevar1($var1,$var2) {
    ob_start();
    var_dump($var1);
    $data = ob_get_clean();
    $data2 = "-------------------------------------------------------\n".$var2."\n". $data . "\n";
    $fp = fopen("/tmp/textfile.txt", "a");
    fwrite($fp, $data2);
    fclose($fp);
}
$view = $this->element->page->getView();
//writevar1($view,'the view on print phtml');
if (true !== $view->db_form_data['summary_form']) {
	$summaryForm = false;
} else {
	$summaryForm = true;
}
if(isset($view->db_form_data['district'])) {
    $district = $view->db_form_data['district'][0];
} else {
    $district = array();
}
echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
echo $this->element->id_form_004;
echo $this->element->page;
?>
<?php if (!$summaryForm || $district['iep_summary_transportation']) :?>
<table class="formSectionHead" cellspacing="0" cellpadding="0">
   <tr>
        <td><?php echo $this->translate('Transportation'); ?></td>
    </tr>
</table>

<table class="formInput" style="margin-top:1px;">
    <tr>
        <TD>
        <table class="formInput" style="margin-top:1px;">
            <tr>
                <td style="text-align: left;" colspan="2">
                    <?php
                        echo "<B>" . $this->element->transportation_yn->getLabel() . "</B> ";
                        echo $this->element->transportation_yn->getMultiOption((int) $this->element->transportation_yn->getValue());
                    ?>
                </td>
            </tr>
            <tr>
                <td>
                    <?php
                        echo "<B>" . $this->element->transportation_why->getLabel() . "</B> ";
                        echo $this->element->transportation_why->getValue();
                    ?>
                </td>
            </tr>
        </table>
        </TD>
    </tr>
</table>
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td><B><?php echo $this->translate('special education transportation'); ?>:</B></td>
    </tr>
    <tr>
        <td>
        <?php
            echo $this->element->transportation_desc->getValue();
        ?>
        </td>
    </tr>
</table>
<?php endif; ?>
<?php if (!$summaryForm || $district['iep_summary_assessment']) :?>
<table class="formSectionHead" cellspacing="0" cellpadding="0">
   <tr>
        <td><?php echo $this->translate('Assessment'); ?></td>
    </tr>
</table>
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td>
        <?php
            if('print' == $view->mode) {
                //echo "<B>" . $this->element->assessment_accom->getLabel() . "</B>";
                if (strlen($this->element->assessment_accom->getValue()) > 0)
                echo "<B>" . $this->translate($this->element->assessment_accom->getValue()) . "</B> ";
            } else {
                echo $this->element->assessment_accom;
            }
        ?></td>
    </tr>
    <tr>
        <td>
            <?php
            if('print' == $view->mode) {
                if($this->element->district_assessments && 'The child will participate in district-wide assessment WITH accommodations, as specified:' != $this->element->assessment_accom->getValue()) {
                    echo $this->element->assessment_desc->getValue();
                } elseif($this->element->district_assessments) {
					echo $this->element->assessment_desc->getValue();
                } else {
                    // old forms
                    echo $this->element->assessment_desc->getValue();
                }
            }
            ?>
            <?php
            if('print' == $view->mode && $this->element->district_assessments) {
                if('The child will participate in district-wide assessment WITH accommodations, as specified:' == $this->element->assessment_accom->getValue()) {
                    echo $this->element->district_assessments->getValue();
                }
            }
            ?>
        </td>
    </tr>
</table>
<table class="formInput" style="margin-top:1px;">
    <tr>
        <td><b><?php echo $this->translate('academic and functional performance'); ?>:</b></td>
    </tr>
    <tr>
        <td>
        <?php
            echo $this->element->assessment_alt->getValue();
        ?>
        </td>
    </tr>
</table>
<?php endif; ?>
<?php if (!$summaryForm || $district['iep_summary_extended_school_services']) :?>
<?php if(!$view->lps || 10 <= $view->version) { ?>
<table class="formSectionHead" cellspacing="0" cellpadding="0">
   <tr>
        <td><?php echo $this->translate('Extended School Year Services'); ?></td>
    </tr>
</table>

<table class="formInput" style="margin-top:1px;">
    <tr>
        <td>
            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                    echo "<B>" . $this->element->ext_school_year_yn->getLabel() . "</B> ";
                    echo $this->element->ext_school_year_yn->getMultiOption((int) $this->element->ext_school_year_yn->getValue());
		        ?>
                </td>
            </tr>
            </table>
        </td>
    </tr>

    <tr>
        <td><B><?php echo $this->translate('child will participate'); ?>:</B></td>
    </tr>
    <tr>
        <td>
        <?php
            echo "<B>" . $this->element->ext_school_year_desc->getLabel() . "</B> ";
            echo $this->element->ext_school_year_desc->getValue();
        ?>
        </td>
    </tr>
</table>
<?php } ?>
<?php endif; ?>

<!-- Mike added this 1-16-2018 for PWN section SRS-151 -->


<?php
$usePWN=new Model_Table_District();
$distInfo=$usePWN->getDistrict($view->db_form_data['id_county'],$view->db_form_data['id_district']);
$distResult=$distInfo['use_form004_pwn'];



if($distResult==true){
?>

<p style="page-break-before: always">



<p>
<b>


</b>






<?php
// Mike added this 1-19-2018 Prior Written Notice
echo $this->studentInfoHeader($view->db_form_data, '004');
?>
<p><br>
<table class="formSectionHead" cellpadding="0" cellspacing="0">

<tr>
            <td><h1><b>Prior Written Notice</b></h1><br></td>
        </tr>
    </table>
<p>



            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                   echo "<B>A description of the action proposed or refused by the school district or approved cooperative.</B><br> ";
                   echo $this->element->pwn_describe_action->getValue();
		        ?>
                </td>
            </tr>
            </table>


<p>
     <tr>
        <td>
            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                  echo "<b>An explanation of why the district or approved cooperative proposes or refuses to take the action: </b><br>";
                   echo $this->element->pwn_describe_reason->getValue();
		        ?>
                </td>
            </tr>
            </table>
        </td>
    </tr>
<p>
     <tr>
        <td>
            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                   echo "<b>A description of other options the IEP team considered and the reasons why those options were rejected:</b><br>";
                   echo $this->element->pwn_options_other->getValue();
		        ?>
                </td>
            </tr>
            </table>

    <p>
            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                   echo "<b>A description of each evaluation procedure, assessment, record or report the school district or approved cooperative uses as a basis for the proposal or refusal: </b><br>";
                    echo $this->element->pwn_justify_action->getValue();
		        ?>
                </td>
            </tr>
            </table>

  <p>

            <table class="formInput" style="margin-top:1px;">
            <tr>
                <td>
		        <?php
                    echo "<b>A description of any other factors which are relevant to the school district’s or approved cooperative’s proposal or refusal:</b><br>";
                    echo $this->element->pwn_other_factors->getValue();
		        ?>
                </td>
            </tr>
            </table>
        </td>
    </tr>
<?php }?>
