<tr>
    <td class="print_bgWhiteSmall" style="text-align:left;padding-left: 8px;"><? echo $this->element->prog_mod; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->prog_mod_from_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->prog_mod_to_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;"><? echo $this->element->prog_mod_location; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->prog_mod_tpd . " " . $this->element->prog_mod_tpd_unit; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->prog_mod_days_value . " " . $this->element->prog_mod_days_unit; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->prog_mod_calendar->getValue(); ?></td>
</tr>
