<table class="formDesc" cellpadding="0" cellspacing="0" >
	<tr>
		<td style="height:21px;">
			<span class="btsb">
				<?= $this->element->subformTitle->getValue(); ?>&nbsp;
				<?= $this->element->count;?>
			</span>
			<?= $this->element->addrow; ?>
			<?= $this->element->add_subform_row; ?>
		</td>
		<td style="height:21px;">
			<a href="javascript:openAccomodationsChecklist('https://iep.unl.eduu/srs.php?area=student&amp;sub=form_004am&amp;student=1322518&amp;id_form_004=1293064&amp;option=new')">Create Modifications/Accommodations Checklist</a>
		</td>
		<td align="right">
			<span class="btsb">
				<?= $this->element->override;?>
			</span>
		</td>
	</tr>
</table>
