<tr>
    <td class="print_bgWhiteSmall" style="text-align:left;padding-left: 8px;"><? echo $this->element->supports; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->school_supp_from_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->school_supp_to_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;"><? echo $this->element->school_supp_location; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->school_supp_tpd . " " . $this->element->school_supp_tpd_unit; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->school_supp_days_value . " " . $this->element->school_supp_days_unit; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->school_supp_calendar->getValue(); ?></td>
</tr>
