<? $rowNum = $this->element->rownumber->getValue(); ?>
<table class="formInput noBorder" border="0" id="supp_services_<?= $rowNum; ?>">
    <tr class="bgLight2">
        <td>
            <?= $rowNum; ?>.
        </td>
        <td>
        	<div id="supp_services_<?= $rowNum; ?>-supp_service-colorme" class="colorme">
            <?= $this->element->supp_service; ?>
            </div>
            <? if('' != $this->element->supp_service->getValue()) { ?>
            	<?php echo $this->translate('If other, specify'); ?>:
            	<?//= $this->element->supp_service; ?>
            <? } ?>
        </td>
        <td class="noprint" style="padding-right:20px;" align="right" >
            <div id="supp_services_<?= $rowNum; ?>-remove_row-colorme" class="colorme">
            <?= $this->element->remove_row; ?>
            </div>
        	<?= $this->element->id_form_004_supp_service; ?>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="supp_services_<?= $rowNum; ?>-dates_wrapper-colorme" class="colorme">
            <?php echo $this->translate('Duration Dates From/To'); ?>: 
            <?= $this->element->supp_service_from_date; ?> <?php echo $this->translate('to'); ?> <?= $this->element->supp_service_to_date; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="supp_services_<?= $rowNum; ?>-supp_service_location-colorme" class="colorme">
            <?php echo $this->translate('Location'); ?> <?= $this->element->supp_service_location; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="supp_services_<?= $rowNum; ?>-tpd_wrapper-colorme" class="colorme" style="white-space:nowrap;">
            <?= $this->element->supp_service_tpd; ?>&nbsp;
            <?= $this->element->supp_service_tpd_unit; ?>
            </div>
            <div id="supp_services_<?= $rowNum; ?>-days_wrapper-colorme" class="colorme" style="white-space:nowrap;">
            <?= $this->element->supp_service_days_value; ?>&nbsp;
            <?= $this->element->supp_service_days_unit; ?>
            </div>
            <div id="supp_services_<?= $rowNum; ?>-supp_service_mpy-colorme" class="colorme" style="white-space:nowrap;">
            <?= $this->element->supp_service_mpy; ?>&nbsp;<span style="margin-left:4px;"><?php echo $this->translate('months'); ?></span>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>
            <div id="supp_services_<?= $rowNum; ?>-supp_service_calendar-colorme" class="colorme">
            <?php echo $this->translate('Does Service Follow School Calendar'); ?>? <?= $this->element->supp_service_calendar; ?>
            </div>
        </td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3"><hr /></td>
    </tr>
</table>
