<tr>
    <td class="print_bgWhiteSmall" style="text-align:left;padding-left: 8px;"><? echo $this->element->supp_service; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->supp_service_from_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo ($this->element->supp_service_to_date); ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;"><? echo $this->element->supp_service_location; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->supp_service_tpd . " " . $this->element->supp_service_tpd_unit; ?></td>
    <td class="print_bgGreySmall" style="text-align:center;white-space: nowrap;"><? //echo $this->element->supp_service_days_value . " " . $this->element->supp_service_days_unit; ?></td>
    <td class="print_bgWhiteSmall" style="text-align:center;white-space: nowrap;"><? echo $this->element->supp_service_calendar->getValue(); ?></td>
</tr>
