<?php 
echo '<input type="hidden" name="returnResult" id="returnResult" value="" />';
echo '<input type="hidden" name="changePageAction" id="changePageAction" value="" />';
echo $this->element->id_form_004;
echo $this->element->page;
?>
<table class="formSectionHead" cellspacing="0" cellpadding="0">
    <tr>
        <td>Transition Plan</td>
    </tr>
</table>
<table class="formInput" style="margin-top:1px;">
	<tr>
		<td>
			<table class="formInput" style="margin:0px; padding:0px;">
				<tr class="bgLight2" style="margin:0px; padding:0px;">
					<td>
					<?= $this->element->transition_plan; ?>
					</td>
					<td><div id="checkboxText">Set up a Transition Plan.</div></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- <div id="subformToChange"></div> -->
<div id="subformToChange" style="<? if(!$this->element->transition_plan->getValue()) echo "visibility:hidden;"; ?>">				
	<table class="formInput" style="margin-top:1px;">        
	     <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		<span><strong>This student will not turn 16 during this IEP, so a statement of the 
	    		child's transition services is not required.</strong></span>
	    	</td>
	    </tr>
	     <tr>
	        <td style="">
	           Complete all that apply, otherwise explain why this item does not apply.
	        </td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		<strong>Measurable post-secondary goals based on age appropriate transition 
	    		assessments: (This section MUST include education/training, employment, 
	    		and when appropriate independent living goals.)</strong>
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td style="text-align: center;">
	    		<strong>Post Secondary Goal(s)</strong>
	    	</td>
	    </tr>
	    <tr>
	    	<td>sdfasdf
			<?php 
				if(isset($view->db_form_data['iep_form_004_secondary_goal'])) {
					$rsCount = $view->subFormsArray['iep_form_004_secondary_goal']->getSubrowsCount(); ?>
					dddd<table id="iep_form_004_secondary_parent" style="width: 100%">
					<tr><td colspan="4">
					<?= $view->form->getSubForm('iep_form_004_secondary_goal'); // header row ?>
					</td>
					</tr>
					<?php 	
					for($x=1; $x <= $rsCount; $x++)
					{
						$idcode = 'id="team_other_container_'.$x.'"';
						echo '<tr '.$idcode.'><td colspan="4">';
						echo $view->form->getSubForm('iep_form_004_secondary_goal_'.$x);
						echo '</td></tr>';
					}
					?>
					</table>
			<?php } ?>
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->post_secondary; ?>
	    	</td>
	    </tr>
	    <tr>
	        <td style="text-align: center;">
	        	<?php echo $this->element->transition_secgoals; ?>
	        </td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		<strong>Course of Study</strong>
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_course_study; ?>
	    	</td>
	    </tr>
	    <tr>
	        <td>
				<strong>Beginning no later than the first IEP to be in effect when the 
				child turns 16, or younger if determined appropriate by the IEP team, 
				a statement of needed transition services is required</strong> (indicate the 
				strengths and/or needs for each area and when appropriate, statement of 
				interagency responsibilities or any needed linkages):
	        </td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Instruction:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_instruction; ?>
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Related Services:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_rel_services; ?>
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Community Experiences:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_comm_exp; ?> 
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
				Development of employment and other appropriate
				<strong>post school adult living objectives: </strong>(i.e. career 
				fair, vocational evaluation, job shadowing, work experience, job seeking 
				and keeping skills, visit college/training programs):
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_emp_options; ?>
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Daily Living Skills:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_dly_liv_skills; ?>
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Functional Vocational Evaluation:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_func_voc_eval; ?>  
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		Interagency Linkages and Responsibilities:
	    	</td>
	    </tr>
	    <tr>
	    	<td>
	    		<?php echo $this->element->transition_16_inter_agency_link; ?>  
	    	</td>
	    </tr>
	    <tr class="bgLight2" style="margin:0px;padding:0px;">
	    	<td>
	    		<table class="formInput" style="margin-top:1px;">
	    			<tr style="width: 100%; background:#EEE8CD; margin:0px;
	    		padding:0px;">
	    				<td>Transition Activities</td>
	    				<td>Agency Responsible</td>
	    				<td>Date Due</td>
	    			</tr>
	    			<tr>
	    				<td><?php echo $this->element->transition_activity1; ?></td>
	    				<td><?php echo $this->element->transition_agency1; ?></td>
	    				<td><?php echo $this->element->transition_date1; ?></td>
	    			</tr>
	    			<tr>
	    				<td><?php echo $this->element->transition_activity2; ?></td>
	    				<td><?php echo $this->element->transition_agency2; ?></td>
	    				<td><?php echo $this->element->transition_date2; ?></td>
	    			</tr>
	    			<tr>
	    				<td><?php echo $this->element->transition_activity3; ?></td>
	    				<td><?php echo $this->element->transition_agency3; ?></td>
	    				<td><?php echo $this->element->transition_date3; ?></td>
	    			</tr>
	    		</table>
	    	</td>
	    </tr>
	</table>
</div>

<?php echo $this->element->submit; ?>
<?php //Zend_debug::dump($this->element->transition_plan->getValue());
