<?php
if (file_exists($this->filename) ) {
    header('Content-type: application/force-download');
    header('Content-Transfer-Encoding: Binary');
    header('Content-length: '.filesize($this->filename));
    header('Content-disposition: attachment;
    filename='.basename($this->filename));
    readfile($this->filename);
} else {
    echo 'No file with this name for download.';
    var_dump($this->filename);
}
?> 
