
<div class="headerHome">
<?php if (!Zend_Auth::getInstance()->hasIdentity()) { ?>
	<p>Returning Customer?&nbsp;&nbsp;<a href="register">Register here.</a>
<?php } ?>
<?php echo $this->loginForm;?></p>
</div>

<!--<div class="iconsHome"></div>-->

<p class="introHome">Lorem ipsum dolor sit amet, consectetuer adipiscing
elit. Cras mollis. Phasellus eu ligula. Sed tortor odio, facilisis at,
ultrices ultrices, mattis non, eros. Quisque ut neque vitae felis
consectetuer molestie.</p>

<p>Cras mollis. Phasellus eu ligula. Sed tortor odio, facilisis at,
ultrices ultrices, mattis non, eros. Quisque ut neque vitae felis
consectetuer molestie. Duis in erat vel ligula volutpat tempus. Nam
sollicitudin consectetuer mauris. Aliquam enim neque, molestie quis,
lacinia quis, feugiat et, purus. Vivamus in quam. Praesent dolor nisl,
porta non, mollis vel, pretium ut, sem. Pellentesque ante tortor,
sollicitudin et, vehicula a, auctor sit amet, enim.</p>


<p><a href="basicsearch">Return to search</a></p>


<!-- end content -->

<!--<div class="footer">-->
<!--<h3>Footer</h3>-->
<!--</div>-->
<!-- end footer -->
