<table style="border: solid 2px black; width: 100%;">
	<tr>
		<td style="text-align: center; width: 90%;">
		<?php echo $this->searchForm; ?>
		<BR>
		</td>
		<td style="text-align: center;">
		<?php echo $this->loginForm; ?>
		</td>
		<td style="text-align: center;">
		<?php echo $this->searchForm2; ?>
		</td>
		<td style="text-align: center;">
		<?php echo print_r($this->searchValues); ?>
		</td>
	</tr>
</table>