

<div>Edit User Detail</div>
<div><a href="/user/view/id/<?= $this->id; ?>">View</a></div>
<BR/>
<?= $this->userForm; ?>

<br/>



<!-- PRIVILEGES -->
<?php if (count($this->privResults) < 1) { ?>
    
    <div>No privileges found.</div>

<?php } else { ?>

    <div><?= count($this->privResults).' results' ?></div>
    <table border="1">
        <tr>
            <th>County</th>
            <th>District</th>
            <th>School</th>
            <th>Class</th>
            <th>Status</th>
        </tr>

        <?php $i = 0; ?>
        <?php foreach ($this->privResults as $k => $r) { ?>
            <tr>
                <td><?= $r['name_county'] ?></td>
                <td><?= $r['name_district'] ?></td>
                <td><?= $r['name_school'] ?></td>
                <td><?= $r['class'] ?></td>
                <td><?= $this->formSelect('priv_id_'.$i++, $r['status'], null, $this->privStatus) ?></td>
            </tr>
        <?php } ?>
        <?= $this->formHidden('priv_count', $i++) ?>
    </table>

<?php }
