

<div>View User Detail</div>
<div><a href="/user/edit/id/<?= $this->id; ?>">Edit</a></div>

<BR/>
<?= $this->userForm; ?>



<!-- PRIVILEGES -->
<?php if (count($this->privResults) < 1) { ?>
    
    <div>No privileges found.</div>

<?php } else { ?>

    <div><?= count($this->privResults).' results' ?></div>
    <table border="1">
        <tr>
            <th>County</th>
            <th>District</th>
            <th>School</th>
            <th>Class</th>
            <th>Status</th>
        </tr>

        <?php foreach ($this->privResults as $k => $r) { ?>
        <?php $i = 0; ?>
            <tr>
                <td><?= $r['name_county'] ?></td>
                <td><?= $r['name_district'] ?></td>
                <td><?= $r['name_school'] ?></td>
                <td><?= $r['class'] ?></td>
                <td><?= $r['status']; ?></td>
            </tr>
            <?php $i++; ?>
        <?php } ?>
    
    </table>

<?php }
