<tr>
    <td>
        <div class="msg_type"><?= ucwords(strtolower($this->msg_type)); ?></div>
    </td>
    <td>
        <div class="msg_title"><?= ucwords(strtolower($this->msg_title)); ?></div>
    </td>
    <td>
    <div class="create_date"><?= ucwords(strtolower($this->create_date)); ?></div>
    </td>
</tr>
<tr class="ajaxListLi">
    <td colspan="3">
        <?= ucwords(strtolower($this->message_text)); ?>
    </td>
</tr>
