<ul id="translationSubNav" class="clearfix">
    <li <?php echo ($this->action == 'index') ? 'class="current"' : ''; ?>><a href="/translation/index">Key Status</a></li>
    <li <?php echo ($this->action == 'manual-key-update') ? 'class="current"' : ''; ?>><a href="/translation/manual-key-update">Manual Key Update</a></li>
    <li <?php echo ($this->action == 'export') ? 'class="current"' : ''; ?>><a href="/translation/export">CSV Export</a></li>
    <li <?php echo ($this->action == 'import') ? 'class="current"' : ''; ?>><a href="/translation/import">CSV Import</a></li>
</ul>