<?
$this->headLink()->appendStylesheet('/css/_layout.css', 'screen');
?>
    <script type="text/javascript">
        $(function () {
            $('#cancel').click(function() {
                window.location.href = '/home/message-center';
                return false;
            });
        });
    </script>
<?php
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/custom/custom_functions.js');

function buildOptionList($pkey, $keyName, $currentValue = "")
{

    global $DOC_ROOT, $area;

    $arrLabel = array("View Message", "Delete Message");
    $arrValue = array("view", "delete");

    $strHTMLSelect = "<select name='option'";
    $strHTMLSelect .= " onChange=\"javascript:if(this.value) { window.location.href = '/home/message-center-'+this.value+'?id=" . $pkey . "'; }\">";

    if (empty($currentValue)) {
        $strHTMLSelect .= "<option value=\"\" selected=\"selected\">Choose...</option>";
    }

    $count = count($arrLabel);

    for ($i = 0; $i < $count; $i++) {
        if ($currentValue == $arrValue[$i]) {
            $strHTMLSelect .= "<option value=\"$arrValue[$i]\" selected=\"selected\">$arrLabel[$i]</option>";
        } else {
            $strHTMLSelect .= "<option value=\"$arrValue[$i]\">$arrLabel[$i]</option>";
        }
    }

    $strHTMLSelect .= "</select>";

    return $strHTMLSelect;
}

?>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#srs_mainPane').css('margin-left', "10px");
        });
    </script>

    <table border="0">
        <!-- logo row -->
        <?php $auth = Zend_Auth::getInstance(); ?>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationTopTabs('simple');
                } ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?php if ($auth->hasIdentity()) {
                    echo $this->navigationSubmenu('home');
                } ?>
            </td>
        </tr>
    </table>
<?
echo $this->form_message;