<?php 
	echo '<div class="page1Portrait">';
    echo $this->header;
	echo $this->footer;
    echo $this->student_header;
    echo $this->pages [1] . '</div>'; // end page 1 div
	echo '<div class="page2Portrait">'.$this->pages[2].'</div>';
	echo '<div class="page3Portrait" style="page-break-before: always;">'.$this->pages[3].'</div>';
	echo '<div class="page4Portrait" style="page-break-before: always;">'.$this->pages[4].'</div>';
	$countOfSuppForms=$this->db_form_data['form_002_suppform']['count'];
	if($countOfSuppForms >0) echo '<div class="page5Portrait" style="page-break-before: always;">'.$this->pages[5].'</div>';
